// ===================================================================
// R39/R40/R41/R42 独立证伪回归（第二层 QA）—— assets/chat-local.js
// 独立于开发自检 verify_r39_chat_0914a.js：造边角场景，尤其
//   - R39 adminPeer 跳过「只对非管理员视角生效」（直接触发 5s 未读轮询回调验证）
//   - R40 lastActive 'YYYY-MM-DD HH:MM:SS' 四类输入 + isOnline 绿点
//   - R41 从未聊过用户 / 带引号昵称 / id 映射 / 重复点击
//   - R42 @username 空值 / 403 / 重复打开 / 普通好友行仍走 openUserHome
// 输出写 tools/qa/_r3943_chat_regression.txt
// ===================================================================
const fs = require('fs');
const path = require('path');
const { JSDOM } = require('jsdom');

const ROOT = 'D:\\cache\\temp\\r44qa_contrast_worktree';
const html = fs.readFileSync(path.join(ROOT, '私聊.html'), 'utf8');
const chatjs = fs.readFileSync(path.join(ROOT, 'assets/chat-local.js'), 'utf8');

const dom = new JSDOM(html, { runScripts: 'outside-only', url: 'http://localhost/' });
const w = dom.window;

let __fetchImpl = function () { return Promise.resolve({ ok: false, status: 403, json: function () { return Promise.resolve({}); } }); };
w.__setFetch = function (fn) { __fetchImpl = fn; };
w.fetch = function () { return __fetchImpl.apply(null, arguments); };
w.__intervals = [];
w.setInterval = function (fn, ms) { w.__intervals.push({ ms: ms, fn: fn }); return w.__intervals.length; };
w.clearInterval = function () {};

w.eval(chatjs);

const H = [];
function L(s) { H.push(s); }
L(';');
L('(async function(){');
L('  var R = [];');
L('  function ck(name, fn){ try { fn(); R.push("PASS " + name); } catch(e){ R.push("FAIL " + name + " :: " + e.message); } }');
L('  async function ckA(name, fn){ try { await fn(); R.push("PASS " + name); } catch(e){ R.push("FAIL " + name + " :: " + e.message); } }');
L('  function a(cond, msg){ if(!cond) throw new Error(msg); }');
L('  function ok(body){ return Promise.resolve({ ok:true, status:200, json:function(){ return Promise.resolve(body); } }); }');
L('  function bad(status, body){ return Promise.resolve({ ok:false, status:status, json:function(){ return Promise.resolve(body||{}); } }); }');
L('  function tick(ms){ return new Promise(function(r){ setTimeout(r, ms||40); }); }');
L('  function setFetch(fn){ window.__setFetch(fn); }');
L('  var T = window.__IM_TEST__;');
L('  if (!T) { window.__R3943_RESULTS = "FAIL setup :: __IM_TEST__ missing"; return; }');
L('  var S = T.S;');
L('  var list = document.getElementById("imList");');
L('  window.localStorage.setItem("study_workbench_token", "tok-r3943");');
L('  window.localStorage.removeItem("xt_admin_user_id");');
L('  setFetch(function(){ return ok({items:[]}); });');
L('');
L('  // R40-1 imFmtLastActive 四类输入');
L('  ck("R40_fmtLastActive_4inputs", function(){');
L('    var f = T.imFmtLastActive;');
L('    a(f("") === "—", "empty should be dash, got [" + f("") + "]");');
L('    a(f("not-a-date") === "—", "invalid should be dash, got [" + f("not-a-date") + "]");');
L('    a(f("2999-01-01 00:00:00") === "刚刚", "future should clamp to justNow, got [" + f("2999-01-01 00:00:00") + "]");');
L('    var now = new Date();');
L('    var p2 = function(n){ return ("0"+n).slice(-2); };');
L('    var justNow = now.getFullYear()+"-"+p2(now.getMonth()+1)+"-"+p2(now.getDate())+" "+p2(now.getHours())+":"+p2(now.getMinutes())+":"+p2(now.getSeconds());');
L('    a(f(justNow) !== "—", "local time string parsed to NaN/dash");');
L('    a(f(justNow) === "刚刚", "just-now should be justNow, got [" + f(justNow) + "]");');
L('    R.push("INFO R40_justNow=" + f(justNow) + " future=" + f("2999-01-01 00:00:00") + " empty=[" + f("") + "] invalid=[" + f("not-a-date") + "]");');
L('  });');
L('');
L('  // R40-2 imAdminUsersHtml 绿点 / 管理员标记 / username 空 / 空列表');
L('  ck("R40_adminUsersHtml_greendot_tag_at_count", function(){');
L('    var items = [');
L('      { id:6, username:"boss", nickname:"admin-A", isAdmin:true, isOnline:true, lastActive:"" },');
L('      { id:7, username:"", nickname:"no-username", isAdmin:false, isOnline:false, lastActive:"2026-01-01 00:00:00" },');
L('      { id:8, username:"neo", nickname:"plain", isAdmin:false, isOnline:false, lastActive:"" }');
L('    ];');
L('    var h = T.imAdminUsersHtml(items);');
L('    a(h.indexOf("全部用户 (3)") !== -1, "missing group title");');
L('    a(h.indexOf("● 在线") !== -1, "isOnline=true missing green dot");');
L('    a(h.indexOf("[管理员]") !== -1, "admin row missing [管理员] tag");');
L('    a(h.indexOf("@boss") !== -1, "should show @boss");');
L('    a(h.indexOf("@neo") !== -1, "should show @neo");');
L('    var at = (h.match(/font-weight:400">@/g) || []).length;');
L('    a(at === 2, "empty-username user must not emit @; at count=" + at);');
L('    var h0 = T.imAdminUsersHtml([]);');
L('    a(h0.indexOf("全部用户 (0)") !== -1, "empty items title should be 全部用户 (0)");');
L('    a(h.indexOf("imOpenChatWithUser(6,") !== -1 && h.indexOf("imOpenChatWithUser(7,") !== -1, "rows missing imOpenChatWithUser entry");');
L('  });');
L('');
L('  // R41 nasty nickname inline onclick safety');
L('  ck("R41_nasty_nickname_onclick_safe", function(){');
L('    var nasty = "a\\u0027b\\u0022c<d>&evil";');
L('    var h = T.imAdminUsersHtml([{ id:9, username:"x", nickname:nasty, isAdmin:false, isOnline:false, lastActive:"" }]);');
L('    var box = document.createElement("div");');
L('    box.innerHTML = h;');
L('    var row = box.querySelector(".im-sess");');
L('    a(!!row, "row with special chars failed to build DOM (onclick broken)");');
L('    var oc = row.getAttribute("onclick") || "";');
L('    a(oc.indexOf("imOpenChatWithUser(9,") === 0, "onclick prefix abnormal: " + oc.slice(0,40));');
L('    var inner = oc.replace(/^imOpenChatWithUser\\(/, "").replace(/\\)\\s*$/, "");');
L('    var args = new Function("return [" + inner + "];")();');
L('    a(args[0] === 9, "first arg should be 9, got " + args[0]);');
L('    a(typeof args[1] === "string" && args[1].indexOf("\\u0027") !== -1 && args[1].indexOf("\\u0022") !== -1 && args[1].indexOf("<") !== -1 && args[1].indexOf("&") !== -1, "nickname did not round-trip, got " + JSON.stringify(args[1]));');
L('    R.push("INFO R41_nasty_roundtrip=" + JSON.stringify(args[1]));');
L('  });');
L('');
L('  // R41 never-chatted / dup click / id mapping');
L('  ck("R41_open_new_user_dedupe_idmap", function(){');
L('    var opened = [];');
L('    var origOpen = window.imOpenChat;');
L('    window.imOpenChat = function(id){ opened.push(id); };');
L('    S.chats = [];');
L('    window.imOpenChatWithUser(7, "\\u5f20\\u4e09", "");');
L('    a(opened.length === 1 && opened[0] === 10007, "never-chatted user did not enter chat, opened=" + JSON.stringify(opened));');
L('    a(S.chats.filter(function(c){ return c.id === 10007; }).length === 1, "should be exactly 1 synthesized chat");');
L('    a(S.chats[0].isServer === true && S.chats[0].serverId === 7, "synthesized chat shape wrong");');
L('    var data = T.loadData();');
L('    a(data.chats["10007"] && data.chats["10007"].isServer === true && data.chats["10007"].serverId === 7, "not persisted with isServer/serverId");');
L('    window.imOpenChatWithUser(7, "\\u5f20\\u4e09", "");');
L('    a(S.chats.filter(function(c){ return c.id === 10007; }).length === 1, "dup click created a 2nd chat row");');
L('    a(opened.length === 2, "dup click should re-enter chat");');
L('    S.chats = [{ id:10008, serverId:8, isServer:true, nickname:"old", avatar:"", last:"", unread:0, time:0 }];');
L('    window.imOpenChatWithUser(8, "newname", "/a.png");');
L('    a(S.chats.length === 1, "existing chat should not add row, got " + S.chats.length);');
L('    a(S.chats[0].nickname === "newname", "existing chat should update nickname");');
L('    a(10000 + 1 > 106, "id mapping 10000+uid may collide with AI friend ids");');
L('    window.imOpenChat = origOpen;');
L('    R.push("INFO R41_id_map_example=" + (10000+7) + " aiMax=106");');
L('  });');
L('');
L('  // R39 ensure/persist/rehydrate/read-zero/getFriend');
L('  ck("R39_ensure_persist_rehydrate_readzero_getfriend", function(){');
L('    S.chats = [];');
L('    var ch = T.imEnsureServerChat({ peerId:6, count:2, lastId:99, last:"hi", nickname:"\\u7ba1\\u7406\\u5458", avatar:"" });');
L('    a(ch && ch.id === 10006 && ch.serverId === 6 && ch.isServer === true, "imEnsureServerChat shape wrong");');
L('    var d = T.loadData();');
L('    a(d.chats["10006"] && d.chats["10006"].isServer === true && d.chats["10006"].serverId === 6, "dynamic chat not persisted");');
L('    S.chats = [];');
L('    T.loadChats();');
L('    var back = S.chats.filter(function(c){ return c.serverId === 6; });');
L('    a(back.length === 1, "after reload should backfill exactly 1, got " + back.length);');
L('    back[0].unread = 0;');
L('    var d2 = T.loadData(); d2.chats["10006"].unread = 0; T.saveData(d2);');
L('    T.loadChats();');
L('    a(S.chats.some(function(c){ return c.serverId === 6; }), "chat row dropped after read-to-zero");');
L('    var gf = T.getFriend(10006);');
L('    a(gf && gf.isServer === true && gf.serverId === 6, "getFriend(10006) did not fall back");');
L('    T.loadChats();');
L('    a(S.chats.filter(function(c){ return c.serverId === 6; }).length === 1, "loadChats produced duplicate rows");');
L('  });');
L('');
L('  // R39/R43 5s unread poll: adminPeer skip only for non-admin view');
L('  await ckA("R39R43_poll_adminPeer_skip_only_nonadmin", async function(){');
L('    var fns = (window.__intervals || []).filter(function(x){ return x.ms === 5000; });');
L('    a(fns.length >= 1, "did not capture 5s unread poll callback (boot not run?)");');
L('    var poll = fns[0].fn;');
L('    S.isAdmin = false;');
L('    window.localStorage.setItem("xt_admin_user_id", "6");');
L('    setFetch(function(url){');
L('      if (String(url).indexOf("/api/chat/unread") >= 0) return ok({ items:[{ peerId:6, count:2, lastId:50, last:"m", nickname:"admin" }] });');
L('      return ok({ items:[] });');
L('    });');
L('    S.chats = [];');
L('    poll();');
L('    await tick(60);');
L('    a(S.chats.filter(function(c){ return c.isServer && c.serverId === 6; }).length === 0, "non-admin receiving admin msg must NOT create row");');
L('    S.chats = [];');
L('    setFetch(function(url){');
L('      if (String(url).indexOf("/api/chat/unread") >= 0) return ok({ items:[{ peerId:7, count:1, lastId:60, last:"hi", nickname:"passerby" }] });');
L('      return ok({ items:[] });');
L('    });');
L('    poll();');
L('    await tick(60);');
L('    a(S.chats.filter(function(c){ return c.isServer && c.serverId === 7; }).length === 1, "non-admin receiving non-admin-nonfriend msg should create row");');
L('    S.isAdmin = true;');
L('    S.chats = [];');
L('    setFetch(function(url){');
L('      if (String(url).indexOf("/api/chat/unread") >= 0) return ok({ items:[{ peerId:6, count:4, lastId:70, last:"x", nickname:"A" }] });');
L('      return ok({ items:[] });');
L('    });');
L('    poll();');
L('    await tick(60);');
L('    a(S.chats.filter(function(c){ return c.isServer && c.serverId === 6; }).length === 1, "admin view must NOT be adminPeer-skipped");');
L('    S.isAdmin = false;');
L('  });');
L('');
L('  // R40-3 admin /api/admin/users 403 -> degrade to /api/friends');
L('  await ckA("R40_403_degrades_to_friends", async function(){');
L('    S.isAdmin = true;');
L('    var called = [];');
L('    setFetch(function(url){');
L('      called.push(String(url));');
L('      if (String(url).indexOf("/api/admin/users") >= 0) return bad(403, {detail:"nope"});');
L('      if (String(url).indexOf("/api/friends") >= 0) return ok({ items:[{ id:7, username:"f", nickname:"friend" }] });');
L('      return ok({ items:[] });');
L('    });');
L('    T.renderFriends(list);');
L('    await tick(180);');
L('    a(called.some(function(u){ return u.indexOf("/api/admin/users") >= 0; }), "admin did not request /api/admin/users first");');
L('    a(called.some(function(u){ return u.indexOf("/api/friends") >= 0; }), "403 did not degrade to /api/friends");');
L('    a(list.innerHTML.indexOf("注册好友") !== -1, "degraded render missing friends list (white screen?)");');
L('  });');
L('');
L('  // R42 regular friend rows still openUserHome');
L('  await ckA("R42_regular_friend_rows_openUserHome", async function(){');
L('    S.isAdmin = false;');
L('    setFetch(function(url){');
L('      if (String(url).indexOf("/api/friends") >= 0) return ok({ items:[{ id:7, username:"fuser", nickname:"friendA", avatar:"", motto:"hi" }] });');
L('      return ok({ items:[] });');
L('    });');
L('    T.renderFriends(list);');
L('    await tick(180);');
L('    var h = list.innerHTML;');
L('    a(h.indexOf("openUserHome(") !== -1, "regular friend row did NOT use openUserHome (regression!)");');
L('    a(h.indexOf("imShowUserProfile(") === -1, "regular friend row wrongly changed to imShowUserProfile");');
L('  });');
L('');
L('  // R42 profile 403 / no stack / close removes');
L('  await ckA("R42_profile_403_no_stack_close", async function(){');
L('    setFetch(function(url){');
L('      if (String(url).indexOf("/api/admin/users/") >= 0) return bad(403, {detail:"forbidden"});');
L('      return ok({ items:[] });');
L('    });');
L('    window.imShowUserProfile(7);');
L('    await tick(80);');
L('    var body = document.getElementById("imUserProfileBody");');
L('    a(!!body, "profile body not created");');
L('    a(body.innerHTML.indexOf("资料加载失败") !== -1, "403 did not show load-failure text");');
L('    window.imShowUserProfile(7);');
L('    window.imShowUserProfile(8);');
L('    await tick(40);');
L('    a(document.querySelectorAll("#imUserProfileModal").length === 1, "duplicate open stacked modals");');
L('    window.imCloseUserProfile();');
L('    a(document.querySelectorAll("#imUserProfileModal").length === 0, "close did not remove DOM");');
L('  });');
L('');
L('  // R42 profile with empty username: no lone @');
L('  await ckA("R42_profile_no_lone_at_when_username_empty", async function(){');
L('    setFetch(function(url){');
L('      if (String(url).indexOf("/api/admin/users/") >= 0) return ok({ id:7, username:"", nickname:"noacct", createdAt:"2026-01-01", lastActive:"", stats:{} });');
L('      return ok({ items:[] });');
L('    });');
L('    window.imShowUserProfile(7);');
L('    await tick(80);');
L('    var body = document.getElementById("imUserProfileBody");');
L('    a(body.innerHTML.indexOf("@") === -1, "empty username must not emit @ in profile, idx=" + body.innerHTML.indexOf("@"));');
L('    window.imCloseUserProfile();');
L('  });');
L('');
L('  window.__R3943_RESULTS = R.join("\\n");');
L('})();');
L('');

setTimeout(function () {
  try { w.eval(H.join('\n')); } catch (e) { w.__R3943_RESULTS = 'HARNESS_EVAL_THROW ' + e.name + ' :: ' + e.message; }
  setTimeout(function () {
    var body = w.__R3943_RESULTS || '(no results)';
    var pass = (body.match(/PASS/g) || []).length;
    var fail = (body.match(/FAIL/g) || []).length;
    var lines = [];
    lines.push('===== R39/R40/R41/R42 独立证伪回归：assets/chat-local.js =====');
    lines.push('取样时间: ' + new Date().toISOString());
    lines.push('捕获 interval 数: ' + (w.__intervals || []).length);
    lines.push('');
    lines.push(body);
    lines.push('');
    lines.push('--- 汇总 ---');
    lines.push('PASS=' + pass + '  FAIL=' + fail);
    lines.push(fail === 0 ? 'RESULT: PASS' : 'RESULT: FAIL');
    var out = lines.join('\n');
    fs.writeFileSync(path.join(ROOT, 'tools/qa/_r3943_chat_regression.txt'), out + '\n');
    console.log(out);
    process.exit(0);
  }, 2500);
}, 350);
