# -*- coding: utf-8 -*-
import os, json
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
existing = set()
ew = os.path.join(root, '_existing_words.txt')
if os.path.exists(ew):
    existing = set(w.strip() for w in open(ew, encoding='utf-8') if w.strip())

# (word, phonetic, meaning)  —— 自撰简明中文释义，规避版权
RAW = [
("gain","/ɡeɪn/","v.获得；增加 n.收益；好处"),
("gas","/ɡæs/","n.气体；汽油"),
("gather","/ˈɡæðə(r)/","v.聚集；收集；逐渐增加"),
("gender","/ˈdʒendə(r)/","n.性别；性（语法）"),
("gene","/dʒiːn/","n.基因"),
("general","/ˈdʒenrəl/","adj.总的；一般的；大体的 n.将军"),
("generate","/ˈdʒenəreɪt/","v.产生；生成；引起"),
("generous","/ˈdʒenərəs/","adj.慷慨的；大方的；丰富的"),
("genuine","/ˈdʒenjuɪn/","adj.真正的；真诚的；非伪造的"),
("gesture","/ˈdʒestʃə(r)/","n.手势；姿态 v.做手势"),
("giant","/ˈdʒaɪənt/","adj.巨大的 n.巨人；伟人"),
("glance","/ɡlɑːns/","v./n.一瞥；扫视"),
("global","/ˈɡləʊbl/","adj.全球的；总的；全面的"),
("glory","/ˈɡlɔːri/","n.荣誉；光荣；辉煌"),
("goods","/ɡʊdz/","n.商品；货物；动产"),
("gradual","/ˈɡrædʒuəl/","adj.逐渐的；逐步的"),
("graduate","/ˈɡrædʒuət/","v.毕业 n.毕业生 adj.研究生的"),
("grand","/ɡrænd/","adj.宏伟的；重大的；壮丽的"),
("grant","/ɡrɑːnt/","v.授予；同意；准予 n.拨款"),
("gravity","/ˈɡrævəti/","n.重力；严重性；庄重"),
("greedy","/ˈɡriːdi/","adj.贪婪的；渴望的"),
("grind","/ɡraɪnd/","v.磨碎；碾；研磨"),
("guarantee","/ˌɡærənˈtiː/","v./n.保证；担保"),
("guard","/ɡɑːd/","v.保卫；看守 n.警卫；守卫"),
("guess","/ɡes/","v./n.猜测；推测"),
("guilty","/ˈɡɪlti/","adj.内疚的；有罪的"),
("guidance","/ˈɡaɪdns/","n.指导；引导；咨询"),
("guide","/ɡaɪd/","v.指导；给…带路 n.指南；导游"),
("handle","/ˈhændl/","v.处理；应付；拿 n.把手；柄"),
("hang","/hæŋ/","v.悬挂；吊；绞死"),
("happen","/ˈhæpən/","v.发生；碰巧"),
("harm","/hɑːm/","n./v.伤害；损害"),
("harsh","/hɑːʃ/","adj.严厉的；粗糙的；刺耳的"),
("harvest","/ˈhɑːvɪst/","n./v.收获；收割；成果"),
("hate","/heɪt/","v.憎恨；厌恶 n.憎恶"),
("headline","/ˈhedlaɪn/","n.标题；头条新闻"),
("heal","/hiːl/","v.治愈；痊愈；修复"),
("healthy","/ˈhelθi/","adj.健康的；健壮的"),
("heap","/hiːp/","n.堆 v.堆积；装满"),
("height","/haɪt/","n.高度；身高；顶点"),
("helpless","/ˈhelpləs/","adj.无助的；无能为力的"),
("hence","/hens/","adv.因此；从此"),
("heroic","/həˈrəʊɪk/","adj.英雄的；英勇的"),
("hesitate","/ˈhezɪteɪt/","v.犹豫；踌躇"),
("highlight","/ˈhaɪlaɪt/","v.强调；突出 n.亮点"),
("highly","/ˈhaɪli/","adv.高度地；非常"),
("hire","/ˈhaɪə(r)/","v.雇用；租用 n.租金"),
("hollow","/ˈhɒləʊ/","adj.空的；空洞的；中空的"),
("honest","/ˈɒnɪst/","adj.诚实的；坦诚的"),
("horizon","/həˈraɪzn/","n.地平线；眼界；视野"),
("host","/həʊst/","n.主人；主持人；大量 v.主办"),
("humble","/ˈhʌmbl/","adj.谦逊的；卑微的 v.使谦卑"),
("humor","/ˈhjuːmə(r)/","n.幽默；情绪"),
("hunt","/hʌnt/","v.打猎；搜寻；追捕"),
("hurry","/ˈhʌri/","v.匆忙；催促 n.急忙"),
("ideal","/aɪˈdɪəl/","adj.理想的 n.理想；典范"),
("identical","/aɪˈdentɪkl/","adj.相同的；一模一样的"),
("identify","/aɪˈdentɪfaɪ/","v.识别；确认；认出"),
("ignore","/ɪɡˈnɔː(r)/","v.忽视；不理睬"),
("illegal","/ɪˈliːɡl/","adj.非法的；违法的"),
("illustrate","/ˈɪləstreɪt/","v.阐明；举例说明；（图书）加插图"),
("image","/ˈɪmɪdʒ/","n.形象；图像；影像"),
("imagine","/ɪˈmædʒɪn/","v.想象；设想；料想"),
("immense","/ɪˈmens/","adj.巨大的；广大的"),
("impact","/ˈɪmpækt/","n./v.影响；冲击；作用"),
("implement","/ˈɪmplɪment/","v.实施；执行 n.工具"),
("imply","/ɪmˈplaɪ/","v.暗示；意味；表明"),
("impose","/ɪmˈpəʊz/","v.强加；征税；迫使"),
("impress","/ɪmˈpres/","v.给…留下印象；使钦佩"),
("improve","/ɪmˈpruːv/","v.改善；改进；提高"),
("incident","/ˈɪnsɪdənt/","n.事件；事变；小插曲"),
("include","/ɪnˈkluːd/","v.包括；包含"),
("increase","/ɪnˈkriːs/","v.增加；增长 n.增加"),
("indeed","/ɪnˈdiːd/","adv.确实；的确；真正地"),
("independent","/ˌɪndɪˈpendənt/","adj.独立的；自主的"),
("indicate","/ˈɪndɪkeɪt/","v.表明；指示；显示"),
("individual","/ˌɪndɪˈvɪdʒuəl/","adj.个人的；单独的 n.个人"),
("industry","/ˈɪndəstri/","n.工业；行业；产业"),
("infer","/ɪnˈfɜː(r)/","v.推断；推论"),
("influence","/ˈɪnfluəns/","n./v.影响；作用"),
("inform","/ɪnˈfɔːm/","v.通知；告知；了解"),
("initial","/ɪˈnɪʃl/","adj.最初的；开头的 n.首字母"),
("injure","/ˈɪndʒə(r)/","v.伤害；损害"),
("innocent","/ˈɪnəsnt/","adj.无辜的；天真的；无罪的"),
("inquire","/ɪnˈkwaɪə(r)/","v.询问；打听；调查"),
("insight","/ˈɪnsaɪt/","n.洞察力；深刻理解"),
("insist","/ɪnˈsɪst/","v.坚持；坚决要求"),
("inspire","/ɪnˈspaɪə(r)/","v.鼓舞；启发；激励"),
("install","/ɪnˈstɔːl/","v.安装；设置；任命"),
("instance","/ˈɪnstəns/","n.例子；实例；情况"),
("instant","/ˈɪnstənt/","adj.立即的；紧急的 n.瞬间"),
("instinct","/ˈɪnstɪŋkt/","n.本能；直觉"),
("institute","/ˈɪnstɪtjuːt/","n.机构；学院；研究所"),
("instruct","/ɪnˈstrʌkt/","v.指导；指示；通知"),
("insure","/ɪnˈʃʊə(r)/","v.给…保险；确保"),
("intend","/ɪnˈtend/","v.打算；想要；意指"),
("intense","/ɪnˈtens/","adj.强烈的；剧烈的；热情的"),
("interact","/ˌɪntərˈækt/","v.互动；相互作用"),
("interest","/ˈɪntrəst/","n.兴趣；利息；利益 v.使感兴趣"),
("interfere","/ˌɪntəˈfɪə(r)/","v.干涉；干扰；妨碍"),
("internal","/ɪnˈtɜːnl/","adj.内部的；国内的；内心的"),
("interpret","/ɪnˈtɜːprɪt/","v.口译；解释；理解"),
("interval","/ˈɪntəvl/","n.间隔；间距；中场休息"),
("interview","/ˈɪntəvjuː/","n./v.面试；采访；会谈"),
("introduce","/ˌɪntrəˈdjuːs/","v.介绍；引进；提出"),
("invent","/ɪnˈvent/","v.发明；创造；虚构"),
("invest","/ɪnˈvest/","v.投资；投入（时间、精力）"),
("investigate","/ɪnˈvestɪɡeɪt/","v.调查；研究"),
("invite","/ɪnˈvaɪt/","v.邀请；招致"),
("involve","/ɪnˈvɒlv/","v.涉及；包含；使卷入"),
("issue","/ˈɪʃuː/","n.问题；议题；发行 v.发布；发行"),
("jealous","/ˈdʒeləs/","adj.嫉妒的；羡慕的"),
("joint","/dʒɔɪnt/","adj.联合的 n.关节；接合处"),
("journey","/ˈdʒɜːni/","n.旅行；旅程 v.旅行"),
("judge","/dʒʌdʒ/","n.法官；裁判 v.判断；裁决"),
("justice","/ˈdʒʌstɪs/","n.正义；司法；公正"),
("justify","/ˈdʒʌstɪfaɪ/","v.证明…正当；为…辩护"),
("keen","/kiːn/","adj.热衷的；敏锐的；强烈的"),
("kindness","/ˈkaɪndnəs/","n.善良；好意"),
("knowledge","/ˈnɒlɪdʒ/","n.知识；学问；了解"),
("labor","/ˈleɪbə(r)/","n.劳动；劳工；分娩 v.劳动"),
("lack","/læk/","n./v.缺乏；不足"),
("landscape","/ˈlændskeɪp/","n.风景；景色 v.美化"),
("largely","/ˈlɑːdʒli/","adv.主要地；大体上；大量地"),
("latter","/ˈlætə(r)/","adj.后者的；后一半的"),
("launch","/lɔːntʃ/","v.发射；发起；推出 n.发射"),
("lawyer","/ˈlɔːjə(r)/","n.律师"),
("layer","/ˈleɪə(r)/","n.层；层次 v.分层放置"),
("lean","/liːn/","v.倾斜；倚；依靠 adj.瘦的；贫乏的"),
("leap","/liːp/","v.跳跃；猛冲 n.飞跃"),
("learned","/ˈlɜːnɪd/","adj.博学的；有学问的"),
("leisure","/ˈleʒə(r)/","n.闲暇；空闲 adj.空闲的"),
("liberal","/ˈlɪbərəl/","adj.自由的；开明的；慷慨的"),
("liberate","/ˈlɪbəreɪt/","v.解放；释放"),
("likely","/ˈlaɪkli/","adj.可能的 adv.很可能"),
("limb","/lɪm/","n.肢；树枝；翼"),
("limit","/ˈlɪmɪt/","n.限制；限度 v.限制"),
("link","/lɪŋk/","v.连接；联系 n.环节；链接"),
("liquid","/ˈlɪkwɪd/","n.液体 adj.液体的；流动的"),
("literary","/ˈlɪtərəri/","adj.文学的；书面的"),
("litter","/ˈlɪtə(r)/","n.垃圾；一窝 v.乱扔"),
("living","/ˈlɪvɪŋ/","adj.活的；活着的 n.生计；生活"),
("locate","/ləʊˈkeɪt/","v.位于；定位；找出"),
("lodge","/lɒdʒ/","v.借宿；存放；提出（投诉）"),
("logical","/ˈlɒdʒɪkl/","adj.逻辑上的；合理的"),
("loose","/luːs/","adj.松的；宽松的；不牢固的"),
("lower","/ˈləʊə(r)/","v.降低；放下 adj.较低的"),
("loyal","/ˈlɔɪəl/","adj.忠诚的；忠心的"),
("luggage","/ˈlʌɡɪdʒ/","n.行李；皮箱"),
("machine","/məˈʃiːn/","n.机器；机械 v.用机器加工"),
("magic","/ˈmædʒɪk/","n.魔法；魔术 adj.神奇的"),
("magnet","/ˈmæɡnət/","n.磁铁；有吸引力的人或物"),
("maintain","/meɪnˈteɪn/","v.维持；保养；坚持认为"),
("major","/ˈmeɪdʒə(r)/","adj.主要的 n.专业；少校 v.主修"),
("manage","/ˈmænɪdʒ/","v.管理；经营；设法做成"),
("manner","/ˈmænə(r)/","n.方式；态度；礼貌（复数）"),
("march","/mɑːtʃ/","v.行进；游行 n.三月；行军"),
("margin","/ˈmɑːdʒɪn/","n.边缘；利润；余地"),
("marine","/məˈriːn/","adj.海洋的；海运的 n.海军陆战队"),
("mark","/mɑːk/","n.标记；分数；痕迹 v.标记；打分"),
("massive","/ˈmæsɪv/","adj.巨大的；大量的；厚重的"),
("mature","/məˈtʃʊə(r)/","adj.成熟的；成年人的 v.成熟"),
("maximum","/ˈmæksɪməm/","adj.最大的 n.最大量；最大限度"),
("meaning","/ˈmiːnɪŋ/","n.意义；含义；意图"),
("means","/miːnz/","n.手段；方法；财富"),
("measure","/ˈmeʒə(r)/","v.测量；衡量 n.措施；尺寸"),
("medium","/ˈmiːdiəm/","adj.中等的 n.媒介；媒体；手段"),
("melt","/melt/","v.融化；熔化；消散"),
("memorial","/məˈmɔːriəl/","adj.纪念的 n.纪念碑；纪念物"),
("mental","/ˈmentl/","adj.精神的；智力的；心理的"),
("mere","/mɪə(r)/","adj.仅仅的；纯粹的"),
("merit","/ˈmerɪt/","n.优点；价值；功绩 v.值得"),
("method","/ˈmeθəd/","n.方法；条理"),
("migrate","/maɪˈɡreɪt/","v.迁移；移居；迁徙"),
("mild","/maɪld/","adj.温和的；轻微的；不严重的"),
("minimum","/ˈmɪnɪməm/","adj.最小的 n.最小值；最低限度"),
("minister","/ˈmɪnɪstə(r)/","n.部长；大臣；牧师"),
("minor","/ˈmaɪnə(r)/","adj.较小的；次要的 n.未成年人"),
("minority","/maɪˈnɒrəti/","n.少数；少数民族"),
("mirror","/ˈmɪrə(r)/","n.镜子 v.反映；反射"),
("mislead","/ˌmɪsˈliːd/","v.误导；使误解"),
("missile","/ˈmɪsaɪl/","n.导弹；发射物"),
("mission","/ˈmɪʃn/","n.使命；任务；代表团"),
("mistake","/mɪˈsteɪk/","n.错误 v.弄错；误解"),
("mixture","/ˈmɪkstʃə(r)/","n.混合；混合物"),
("mode","/məʊd/","n.方式；模式；状态"),
("moderate","/ˈmɒdərət/","adj.适度的；温和的；中等的"),
("modify","/ˈmɒdɪfaɪ/","v.修改；更改；修饰"),
("moral","/ˈmɒrəl/","adj.道德的；精神上的 n.道德；寓意"),
("moreover","/mɔːrˈəʊvə(r)/","adv.此外；而且"),
("mostly","/ˈməʊstli/","adv.主要地；通常；多半"),
("motion","/ˈməʊʃn/","n.运动；动作；动议 v.打手势"),
("motivate","/ˈməʊtɪveɪt/","v.激励；激发；成为…动机"),
("motive","/ˈməʊtɪv/","n.动机；目的 adj.发动的"),
("mount","/maʊnt/","v.登上；安装；增加 n.山；底座"),
("mutual","/ˈmjuːtʃuəl/","adj.相互的；共同的"),
("mystery","/ˈmɪstri/","n.神秘（的事）；谜"),
("naked","/ˈneɪkɪd/","adj.裸体的；无遮蔽的；明显的"),
("narrow","/ˈnærəʊ/","adj.狭窄的 v.变窄；缩小"),
("native","/ˈneɪtɪv/","adj.本地的；天生的 n.本地人"),
("natural","/ˈnætʃrəl/","adj.自然的；天然的；天生的"),
("navy","/ˈneɪvi/","n.海军；深蓝色"),
("neat","/niːt/","adj.整洁的；灵巧的；简洁的"),
("needle","/ˈniːdl/","n.针；指针；注射针"),
("negative","/ˈneɡətɪv/","adj.消极的；否定的；负的 n.底片"),
("negotiate","/nɪˈɡəʊʃieɪt/","v.谈判；协商；商定"),
("nest","/nest/","n.巢；窝 v.筑巢"),
("network","/ˈnetwɜːk/","n.网络；网状系统；广播网"),
("neutral","/ˈnjuːtrəl/","adj.中立的；中性的；平淡的"),
("noble","/ˈnəʊbl/","adj.高尚的；贵族的 n.贵族"),
("noise","/nɔɪz/","n.噪音；响声；干扰"),
("normal","/ˈnɔːml/","adj.正常的；标准的 n.常态"),
("noticeable","/ˈnəʊtɪsəbl/","adj.明显的；显著的"),
("nowhere","/ˈnəʊweə(r)/","adv.无处；任何地方都不"),
("nuclear","/ˈnjuːkliə(r)/","adj.核能的；核的；核心的"),
("numerous","/ˈnjuːmərəs/","adj.众多的；许多的"),
("obey","/əˈbeɪ/","v.服从；遵守；听从"),
("object","/ˈɒbdʒɪkt/","n.物体；目标；宾语 /əbˈdʒekt/ v.反对"),
("oblige","/əˈblaɪdʒ/","v.迫使；帮忙；使感激"),
("observe","/əbˈzɜːv/","v.观察；遵守；庆祝"),
("obstacle","/ˈɒbstəkl/","n.障碍；妨碍"),
("obtain","/əbˈteɪn/","v.获得；得到"),
("obvious","/ˈɒbviəs/","adj.明显的；显而易见的"),
("occasion","/əˈkeɪʒn/","n.场合；时机；特殊事件"),
("occupy","/ˈɒkjupaɪ/","v.占据；占用；使忙碌"),
("occur","/əˈkɜː(r)/","v.发生；出现；存在"),
("odd","/ɒd/","adj.奇怪的；奇数的；剩余的"),
("offend","/əˈfend/","v.冒犯；触怒；违反"),
("offer","/ˈɒfə(r)/","v.提供；提议 n.提议；出价"),
("official","/əˈfɪʃl/","adj.官方的；正式的 n.官员"),
("omit","/əˈmɪt/","v.省略；遗漏；疏忽"),
("operate","/ˈɒpəreɪt/","v.操作；运转；动手术；经营"),
("opinion","/əˈpɪnjən/","n.意见；看法；舆论"),
("opponent","/əˈpəʊnənt/","n.对手；反对者 adj.对立的"),
("opportunity","/ˌɒpəˈtjuːnəti/","n.机会；时机"),
("oppose","/əˈpəʊz/","v.反对；反抗"),
("optimistic","/ˌɒptɪˈmɪstɪk/","adj.乐观的；乐观主义的"),
("optional","/ˈɒpʃənl/","adj.可选的；非强制的"),
("orbit","/ˈɔːbɪt/","n.轨道 v.绕轨道运行"),
("order","/ˈɔːdə(r)/","n.命令；顺序；订单；秩序 v.命令；订购"),
("ordinary","/ˈɔːdnri/","adj.普通的；平常的；平凡的"),
("organ","/ˈɔːɡən/","n.器官；机构；风琴"),
("organize","/ˈɔːɡənaɪz/","v.组织；筹备；安排"),
("origin","/ˈɒrɪdʒɪn/","n.起源；出身；起因"),
("otherwise","/ˈʌðəwaɪz/","adv.否则；除此以外 conj.否则"),
("outcome","/ˈaʊtkʌm/","n.结果；后果；成果"),
("outline","/ˈaʊtlaɪn/","n.大纲；轮廓 v.概述；画轮廓"),
("outlook","/ˈaʊtlʊk/","n.观点；前景；景色"),
("output","/ˈaʊtpʊt/","n.产量；输出；产出"),
("outstanding","/aʊtˈstændɪŋ/","adj.杰出的；出色的；未解决的"),
("oval","/ˈəʊvl/","adj.椭圆形的 n.椭圆"),
("overall","/ˌəʊvərˈɔːl/","adj.总体的；全面的 adv.总共；大体上"),
("overcome","/ˌəʊvəˈkʌm/","v.克服；战胜；征服"),
("overhead","/ˌəʊvəˈhed/","adj.在头顶上的 adv.在头顶；在空中"),
("overlook","/ˌəʊvəˈlʊk/","v.俯瞰；忽略；宽恕"),
("owe","/əʊ/","v.欠；归功于；感激"),
("own","/əʊn/","adj.自己的 v.拥有；承认"),
("packet","/ˈpækɪt/","n.小包；小袋；数据包"),
("painful","/ˈpeɪnfl/","adj.痛苦的；疼痛的；艰难的"),
("painter","/ˈpeɪntə(r)/","n.画家；油漆工"),
("palace","/ˈpæləs/","n.宫殿；豪华住宅"),
("panic","/ˈpænɪk/","n.恐慌；惊慌 v.使恐慌"),
("parade","/pəˈreɪd/","n./v.游行；阅兵；炫耀"),
("parallel","/ˈpærəlel/","adj.平行的；类似的 n.平行线；相似处"),
("parcel","/ˈpɑːsl/","n.包裹；小包 v.打包"),
("pardon","/ˈpɑːdn/","n./v.原谅；赦免；宽恕"),
("particular","/pəˈtɪkjələ(r)/","adj.特定的；特别的；挑剔的"),
("partner","/ˈpɑːtnə(r)/","n.伙伴；搭档；配偶"),
("passive","/ˈpæsɪv/","adj.被动的；消极的；被动语态的"),
("patch","/pætʃ/","n.补丁；小块；斑 v.修补；打补丁"),
("patient","/ˈpeɪʃnt/","adj.耐心的 n.病人"),
("pattern","/ˈpætn/","n.模式；图案；样式 v.仿制"),
("pause","/pɔːz/","v./n.暂停；中止；停顿"),
("peaceful","/ˈpiːsfl/","adj.和平的；安静的；安宁的"),
("peak","/piːk/","n.山峰；顶点；顶峰 v.达到高峰"),
("peculiar","/pɪˈkjuːliə(r)/","adj.独特的；奇怪的；特有的"),
("penetrate","/ˈpenətreɪt/","v.穿透；渗透；看穿"),
("pension","/ˈpenʃn/","n.养老金；退休金"),
("perceive","/pəˈsiːv/","v.察觉；感知；理解"),
("perform","/pəˈfɔːm/","v.执行；表演；表现"),
("permanent","/ˈpɜːmənənt/","adj.永久的；持久的"),
("permission","/pəˈmɪʃn/","n.许可；允许；同意"),
("persist","/pəˈsɪst/","v.坚持；持续存在"),
("personal","/ˈpɜːsənl/","adj.个人的；私人的；亲自的"),
("persuade","/pəˈsweɪd/","v.说服；劝说"),
("pessimistic","/ˌpesɪˈmɪstɪk/","adj.悲观的；悲观主义的"),
("phenomenon","/fəˈnɒmɪnən/","n.现象；非凡的人或事"),
("phrase","/freɪz/","n.短语；习惯用语；措辞 v.表达"),
("physical","/ˈfɪzɪkl/","adj.身体的；物理的；物质的"),
("pile","/paɪl/","n.堆；大量 v.堆积；堆叠"),
("pill","/pɪl/","n.药丸；药片"),
("pillar","/ˈpɪlə(r)/","n.柱子；栋梁；核心人物"),
("pin","/pɪn/","n.别针；针；销 v.钉住；固定"),
("pipe","/paɪp/","n.管子；烟斗；管乐器 v.用管道输送"),
("platform","/ˈplætfɔːm/","n.平台；站台；讲台"),
("player","/ˈpleɪə(r)/","n.运动员；玩家；播放器"),
("plot","/plɒt/","n.情节；阴谋；小块土地 v.密谋；绘图"),
("plunge","/plʌndʒ/","v.跳入；骤降；陷入 n.猛跌"),
("plural","/ˈplʊərəl/","adj.复数的 n.复数"),
("poem","/ˈpəʊɪm/","n.诗；诗篇"),
("poet","/ˈpəʊɪt/","n.诗人"),
("poison","/ˈpɔɪzn/","n.毒药；毒物 v.毒害；下毒"),
("polite","/pəˈlaɪt/","adj.有礼貌的；客气的；优雅的"),
("political","/pəˈlɪtɪkl/","adj.政治的；政治上的"),
("pollute","/pəˈluːt/","v.污染；弄脏；腐蚀"),
("port","/pɔːt/","n.港口；口岸；端口"),
("portion","/ˈpɔːʃn/","n.部分；一份 v.分配"),
("pose","/pəʊz/","v.造成；摆姿势；提出 n.姿势"),
("positive","/ˈpɒzətɪv/","adj.积极的；肯定的；正的"),
("possess","/pəˈzes/","v.拥有；占有；具备"),
("postpone","/pəˈspəʊn/","v.推迟；延期"),
("potential","/pəˈtenʃl/","adj.潜在的；可能的 n.潜力；潜能"),
("poverty","/ˈpɒvəti/","n.贫困；贫穷；贫乏"),
("powder","/ˈpaʊdə(r)/","n.粉末；粉 v.洒粉"),
("practical","/ˈpræktɪkl/","adj.实际的；实用的；务实的"),
("pray","/preɪ/","v.祈祷；祈求；恳求"),
("precious","/ˈpreʃəs/","adj.珍贵的；宝贵的；珍稀的"),
("precise","/prɪˈsaɪs/","adj.精确的；准确的；恰好的"),
("predict","/prɪˈdɪkt/","v.预测；预言；预告"),
("prefer","/prɪˈfɜː(r)/","v.更喜欢；宁愿"),
("pregnant","/ˈpreɡnənt/","adj.怀孕的；孕育的；含蓄的"),
("prejudice","/ˈpredʒudɪs/","n.偏见；成见 v.使有偏见"),
("preliminary","/prɪˈlɪmɪnəri/","adj.初步的；预备的 n.准备工作"),
("prepare","/prɪˈpeə(r)/","v.准备；筹备；使准备好"),
("presence","/ˈprezns/","n.出席；存在；在场"),
("present","/ˈpreznt/","adj.出席的；现在的 n.礼物；现在 /prɪˈzent/ v.呈现；赠送；提出"),
("preserve","/prɪˈzɜːv/","v.保护；保存；腌制"),
("prevail","/prɪˈveɪl/","v.流行；盛行；获胜；占上风"),
("prevent","/prɪˈvent/","v.防止；阻止；预防"),
("previous","/ˈpriːviəs/","adj.先前的；以前的；早先的"),
("primary","/ˈpraɪməri/","adj.主要的；初级的；首要的"),
("primitive","/ˈprɪmətɪv/","adj.原始的；简陋的；早期的"),
("principal","/ˈprɪnsəpl/","adj.主要的；首要的 n.校长；本金"),
("principle","/ˈprɪnsəpl/","n.原则；原理；准则"),
("prior","/ˈpraɪə(r)/","adj.优先的；在先的；之前的"),
("priority","/praɪˈɒrəti/","n.优先（的事）；优先权；重点"),
("private","/ˈpraɪvət/","adj.私人的；私下的；私营的"),
("probable","/ˈprɒbəbl/","adj.很可能发生的；大概的"),
("procedure","/prəˈsiːdʒə(r)/","n.程序；步骤；手续"),
("proceed","/prəˈsiːd/","v.继续进行；着手；前进"),
("process","/ˈprəʊses/","n.过程；工序；程序 v.处理；加工"),
("produce","/prəˈdjuːs/","v.生产；产生；制造；引起"),
("product","/ˈprɒdʌkt/","n.产品；产物；乘积"),
("professional","/prəˈfeʃənl/","adj.专业的；职业的 n.专业人士"),
("profile","/ˈprəʊfaɪl/","n.轮廓；简介；侧面 v.概述"),
("profit","/ˈprɒfɪt/","n.利润；收益 v.获益；有益于"),
("profound","/prəˈfaʊnd/","adj.深刻的；深厚的；深奥的"),
("program","/ˈprəʊɡræm/","n.节目；计划；程序；课程 v.编程"),
("progress","/ˈprəʊɡres/","n.进步；进展 /prəˈɡres/ v.前进；进步"),
("prohibit","/prəˈhɪbɪt/","v.禁止；阻止；妨碍"),
("project","/ˈprɒdʒekt/","n.项目；工程；计划 /prəˈdʒekt/ v.投射；规划；伸出"),
("prominent","/ˈprɒmɪnənt/","adj.突出的；杰出的；显著的"),
("promise","/ˈprɒmɪs/","n./v.承诺；诺言；预示"),
("promote","/prəˈməʊt/","v.促进；提升；推销；倡导"),
("prompt","/prɒmpt/","adj.迅速的；及时的；敏捷的 v.促使；提示"),
("proof","/pruːf/","n.证据；证明；检验 adj.防…的"),
("proper","/ˈprɒpə(r)/","adj.适当的；正确的；合乎体统的"),
("property","/ˈprɒpəti/","n.财产；性质；特性；房地产"),
("proposal","/prəˈpəʊzl/","n.提议；建议；求婚"),
("prospect","/ˈprɒspekt/","n.前景；可能性；景色 /prəˈspekt/ v.勘探"),
("protect","/prəˈtekt/","v.保护；防护；保卫"),
("protest","/ˈprəʊtest/","n./v.抗议；反对；声明"),
("proud","/praʊd/","adj.自豪的；骄傲的；引以为荣的"),
("prove","/pruːv/","v.证明；证实；结果是"),
("provide","/prəˈvaɪd/","v.提供；供给；规定"),
("publish","/ˈpʌblɪʃ/","v.出版；发布；公布；发表"),
("punctual","/ˈpʌŋktʃuəl/","adj.准时的；守时的"),
("punish","/ˈpʌnɪʃ/","v.惩罚；处罚；惩处"),
("purchase","/ˈpɜːtʃəs/","v.购买；采购 n.购买；购得物"),
("purpose","/ˈpɜːpəs/","n.目的；意图；用途 v.打算"),
("pursue","/pəˈsjuː/","v.追求；追赶；从事；继续"),
("puzzle","/ˈpʌzl/","n.谜；困惑；拼图 v.使迷惑；苦思"),
("qualify","/ˈkwɒlɪfaɪ/","v.使合格；取得资格；胜任"),
("quality","/ˈkwɒləti/","n.质量；品质；特性 adj.优质的"),
("quantity","/ˈkwɒntəti/","n.数量；数额；大量"),
("quarrel","/ˈkwɒrəl/","n./v.争吵；吵架；不和"),
("quarter","/ˈkwɔːtə(r)/","n.四分之一；季度；一刻钟"),
("queer","/kwɪə(r)/","adj.奇怪的；异常的；不舒服的"),
("quit","/kwɪt/","v.离开；放弃；辞职；停止"),
("quiz","/kwɪz/","n.小测验；智力竞赛 v.测验；盘问"),
("quote","/kwəʊt/","v.引用；引述；报价 n.引文；报价"),
("racial","/ˈreɪʃl/","adj.种族的；人种的"),
("rack","/ræk/","n.架子；支架；痛苦 v.使痛苦；折磨"),
("radiation","/ˌreɪdiˈeɪʃn/","n.辐射；放射；辐射物"),
("radical","/ˈrædɪkl/","adj.根本的；激进的；彻底的 n.激进分子"),
("rail","/reɪl/","n.栏杆；铁轨；扶手 v.抱怨；铁路运输"),
("rainbow","/ˈreɪnbəʊ/","n.彩虹；五彩缤纷的事物"),
("range","/reɪndʒ/","n.范围；幅度；山脉 v.变化；变动；涉及"),
("rank","/ræŋk/","n.等级；军衔；排名 v.排列；位列"),
("rare","/reə(r)/","adj.稀有的；罕见的；稀薄的"),
("rate","/reɪt/","n.比率；速度；价格 v.评估；值得"),
("rather","/ˈrɑːðə(r)/","adv.相当；宁愿；更准确地说"),
("raw","/rɔː/","adj.生的；未经加工的；原始的；擦伤的"),
("react","/riˈækt/","v.反应；回应；反对"),
("readily","/ˈredɪli/","adv.乐意地；容易地；很快地"),
("realistic","/ˌriːəˈlɪstɪk/","adj.现实的；逼真的；实际的"),
("realm","/relm/","n.领域；王国；范畴"),
("rear","/rɪə(r)/","adj.后面的；后方的 n.后部；后方 v.抚养；饲养"),
("reasonable","/ˈriːznəbl/","adj.合理的；适度的；明智的"),
("rebel","/ˈrebl/","n.反叛者；叛逆者 /rɪˈbel/ v.反叛；反抗"),
("recall","/rɪˈkɔːl/","v.回忆；召回；收回"),
("receipt","/rɪˈsiːt/","n.收据；收条；收到"),
("receive","/rɪˈsiːv/","v.收到；接收；接待；遭受"),
("recent","/ˈriːsnt/","adj.最近的；近来的；新近的"),
("reckon","/ˈrekən/","v.认为；估计；计算；指望"),
("recognition","/ˌrekəɡˈnɪʃn/","n.认出；识别；认可；表彰"),
("recommend","/ˌrekəˈmend/","v.推荐；建议；劝告"),
("record","/ˈrekɔːd/","n.记录；唱片；最高纪录 /rɪˈkɔːd/ v.记录；录音"),
("recover","/rɪˈkʌvə(r)/","v.恢复；找回；康复"),
("recycle","/ˌriːˈsaɪkl/","v.回收；再利用；循环"),
("reduce","/rɪˈdjuːs/","v.减少；降低；缩减；使沦为"),
("reflect","/rɪˈflekt/","v.反映；反射；思考；映出"),
("reform","/rɪˈfɔːm/","v./n.改革；改良；改造"),
("refresh","/rɪˈfreʃ/","v.使恢复精力；更新；使清新"),
("refuse","/rɪˈfjuːz/","v.拒绝；不接受；不愿"),
("regard","/rɪˈɡɑːd/","v.认为；看待；注视 n.尊敬；问候；注意"),
("regime","/reɪˈʒiːm/","n.政权；制度；管理体制"),
("region","/ˈriːdʒən/","n.地区；区域；行政区"),
("register","/ˈredʒɪstə(r)/","v.登记；注册；挂号 n.登记簿"),
("regret","/rɪˈɡret/","v./n.后悔；遗憾；惋惜"),
("regular","/ˈreɡjələ(r)/","adj.规律的；定期的；正规的；整齐的"),
("reject","/rɪˈdʒekt/","v.拒绝；排斥；退回 n.次品"),
("relate","/rɪˈleɪt/","v.联系；涉及；讲述；有关"),
("release","/rɪˈliːs/","v.释放；发布；解除；上映 n.发布；发行"),
("relevant","/ˈreləvənt/","adj.相关的；切题的；有价值的"),
("relief","/rɪˈliːf/","n.缓解；减轻；救济；宽慰"),
("rely","/rɪˈlaɪ/","v.依赖；依靠；信赖"),
("remain","/rɪˈmeɪn/","v.保持；仍然是；剩余；留下"),
("remark","/rɪˈmɑːk/","v.评论；谈论；注意 n.言论；备注"),
("remedy","/ˈremədi/","n.补救；治疗；药品 v.补救；纠正"),
("remind","/rɪˈmaɪnd/","v.提醒；使想起"),
("remote","/rɪˈməʊt/","adj.遥远的；偏远的；疏远的"),
("remove","/rɪˈmuːv/","v.移走；去除；开除；搬迁"),
("render","/ˈrendə(r)/","v.使得；提供；给予；翻译；呈现"),
("rent","/rent/","v.租；出租 n.租金；房租"),
("repair","/rɪˈpeə(r)/","v.修理；修复；弥补 n.修理"),
("repeat","/rɪˈpiːt/","v.重复；重说；复述 n.重复"),
("replace","/rɪˈpleɪs/","v.取代；更换；把…放回原处"),
("represent","/ˌreprɪˈzent/","v.代表；象征；描绘；相当于"),
("republic","/rɪˈpʌblɪk/","n.共和国；共和政体"),
("reputation","/ˌrepjuˈteɪʃn/","n.声誉；名声；名望"),
("request","/rɪˈkwest/","n./v.请求；要求；需求"),
("require","/rɪˈkwaɪə(r)/","v.需要；要求；规定；命令"),
("rescue","/ˈreskjuː/","v.救援；营救 n.救援"),
("reserve","/rɪˈzɜːv/","v.保留；预订；储备 n.储备；自然保护区"),
("resign","/rɪˈzaɪn/","v.辞职；放弃；顺从"),
("resist","/rɪˈzɪst/","v.抵制；抵抗；忍住"),
("resolve","/rɪˈzɒlv/","v.解决；决心；决定 n.决心；决意"),
("resort","/rɪˈzɔːt/","v.求助；诉诸 n.度假胜地；手段"),
("resource","/rɪˈsɔːs/","n.资源；财力；办法"),
("respect","/rɪˈspekt/","n./v.尊敬；尊重；方面；关系"),
("respond","/rɪˈspɒnd/","v.回应；回答；作出反应"),
("restore","/rɪˈstɔː(r)/","v.恢复；修复；归还"),
("restrain","/rɪˈstreɪn/","v.抑制；约束；制止"),
("restrict","/rɪˈstrɪkt/","v.限制；约束；限定"),
("retain","/rɪˈteɪn/","v.保留；保持；留用"),
("retire","/rɪˈtaɪə(r)/","v.退休；退职；退出"),
("reveal","/rɪˈviːl/","v.揭示；显露；透露；展现"),
("revenue","/ˈrevənjuː/","n.收入；收益；税收"),
("reverse","/rɪˈvɜːs/","v.反转；颠倒 adj.相反的；反向的 n.相反；倒车"),
("review","/rɪˈvjuː/","n./v.复习；评论；回顾；审查"),
("revise","/rɪˈvaɪz/","v.修订；修改；复习"),
("revolve","/rɪˈvɒlv/","v.旋转；环绕；围绕"),
("reward","/rɪˈwɔːd/","n.报酬；奖励；回报 v.奖励；报答"),
("rhythm","/ˈrɪðəm/","n.节奏；韵律；规律"),
("ridiculous","/rɪˈdɪkjələs/","adj.荒谬的；可笑的；荒唐的"),
("rigid","/ˈrɪdʒɪd/","adj.僵硬的；严格的；死板的"),
("ripe","/raɪp/","adj.成熟的；时机成熟的"),
("rival","/ˈraɪvl/","n.对手；竞争者 v.与…竞争；比得上"),
("roll","/rəʊl/","v.滚动；卷；摇晃 n.卷；名册；面包卷"),
("romantic","/rəʊˈmæntɪk/","adj.浪漫的；浪漫主义的；不切实际的"),
("root","/ruːt/","n.根；根源；词根 v.扎根；根除"),
("rotate","/rəʊˈteɪt/","v.旋转；（使）轮流；轮换"),
("rough","/rʌf/","adj.粗糙的；粗略的；艰苦的；波涛汹涌的"),
("route","/ruːt/","n.路线；航线；途径 v.按路线发送"),
("routine","/ruːˈtiːn/","n.常规；例行公事；固定程序 adj.常规的"),
("royal","/ˈrɔɪəl/","adj.皇家的；王室的；高贵的"),
("rude","/ruːd/","adj.粗鲁的；无礼的；粗糙的"),
("ruin","/ˈruːɪn/","v.毁灭；毁坏 n.废墟；毁灭"),
("rural","/ˈrʊərəl/","adj.农村的；乡村的；田园的"),
("sacrifice","/ˈsækrɪfaɪs/","n./v.牺牲；献祭；舍弃"),
("sake","/seɪk/","n.缘故；理由；利益"),
("salary","/ˈsæləri/","n.薪水；工资（按月发）"),
("sample","/ˈsɑːmpl/","n.样本；样品；例子 v.抽样；品尝"),
("satisfy","/ˈsætɪsfaɪ/","v.使满意；满足；符合"),
("scale","/skeɪl/","n.规模；比例；天平；刻度 v.缩放；攀登"),
("scan","/skæn/","v.扫描；浏览；细看 n.扫描"),
("scatter","/ˈskætə(r)/","v.散开；散布；驱散"),
("scene","/siːn/","n.场景；景象；现场；镜头"),
("scheme","/skiːm/","n.计划；方案；阴谋 v.策划；密谋"),
("scholar","/ˈskɒlə(r)/","n.学者；奖学金获得者"),
("scope","/skəʊp/","n.范围；余地；视野；机会"),
("score","/skɔː(r)/","n.分数；得分；二十 v.得分；评分"),
("scrape","/skreɪp/","v.刮；擦；刮掉 n.擦伤；刮擦声"),
("scratch","/skrætʃ/","v.抓；搔；刮 n.抓痕；起跑线"),
("screen","/skriːn/","n.屏幕；屏风；筛 v.筛查；放映；遮挡"),
("sculpture","/ˈskʌlptʃə(r)/","n.雕塑；雕刻；雕像 v.雕刻"),
("section","/ˈsekʃn/","n.部分；章节；部门；截面"),
("secure","/sɪˈkjʊə(r)/","adj.安全的；稳固的 v.获得；保护；系牢"),
("select","/sɪˈlekt/","v.选择；挑选 adj.精选的；优等的"),
("senior","/ˈsiːniə(r)/","adj.资深的；年长的；高年级的 n.长辈；上司"),
("sensible","/ˈsensəbl/","adj.明智的；合理的；务实的"),
("sensitive","/ˈsensətɪv/","adj.敏感的；灵敏的；易受伤的"),
("separate","/ˈseprət/","adj.分开的；单独的 /ˈsepəreɪt/ v.分开；分离；区分"),
("sequence","/ˈsiːkwəns/","n.顺序；序列；连续；后果"),
("series","/ˈsɪəriːz/","n.系列；丛书；连续"),
("severe","/sɪˈvɪə(r)/","adj.严重的；严厉的；剧烈的"),
("sexual","/ˈsekʃuəl/","adj.性的；性别的；生殖的"),
("shade","/ʃeɪd/","n.阴影；阴凉处；色调 v.遮蔽；使阴暗"),
("shadow","/ˈʃædəʊ/","n.影子；阴影；荫 v.跟踪；庇荫"),
("shallow","/ˈʃæləʊ/","adj.浅的；肤浅的；表面的"),
("shame","/ʃeɪm/","n.羞耻；憾事；可耻的人 v.使羞愧"),
("shape","/ʃeɪp/","n.形状；外形 v.塑造；影响；形成"),
("share","/ʃeə(r)/","v.分享；分担；分摊 n.份额；股份"),
("sharp","/ʃɑːp/","adj.锋利的；敏锐的；急剧的； sharply adv."),
("shelter","/ˈʃeltə(r)/","n.遮蔽；避难所；住所 v.庇护；躲避"),
("shift","/ʃɪft/","v.转移；变换；移动 n.轮班；转变"),
("shock","/ʃɒk/","n.震惊；冲击；休克 v.使震惊；震动"),
("shoot","/ʃuːt/","v.射击；拍摄；发芽 n.嫩芽； shoots"),
("shore","/ʃɔː(r)/","n.岸；滨 v.支撑；稳住"),
("shortage","/ˈʃɔːtɪdʒ/","n.短缺；不足；缺乏"),
("sight","/saɪt/","n.视力；景象；视野 v.看见；瞄准"),
("signal","/ˈsɪɡnəl/","n.信号；暗号 v.发信号；示意 adj.重大的"),
("significant","/sɪɡˈnɪfɪkənt/","adj.重要的；显著的；有意义的"),
("similar","/ˈsɪmələ(r)/","adj.相似的；类似的；像"),
("sincere","/sɪnˈsɪə(r)/","adj.真诚的；诚挚的；真诚的"),
("sketch","/sketʃ/","n.素描；草图；梗概 v.勾勒；简述"),
("skilled","/skɪld/","adj.熟练的；有技能的；需要技能的"),
("skim","/skɪm/","v.略读；撇去；掠过"),
("slight","/slaɪt/","adj.轻微的；少量的；纤细的 v.轻视"),
("slip","/slɪp/","v.滑倒；溜走；脱落 n.小错误；便条"),
("smooth","/smuːð/","adj.光滑的；顺利的；平稳的 v.使平滑"),
("social","/ˈsəʊʃl/","adj.社会的；社交的；群居的"),
("sole","/səʊl/","adj.唯一的；单独的 n.脚底；鞋底"),
("solemn","/ˈsɒləm/","adj.庄严的；严肃的；隆重的"),
("solid","/ˈsɒlɪd/","adj.固体的；可靠的；实心的 n.固体"),
("solution","/səˈluːʃn/","n.解决（办法）；溶液；溶解"),
("solve","/sɒlv/","v.解决；解答；解开"),
("somewhat","/ˈsʌmwɒt/","adv.有点；稍微；在某种程度上"),
("source","/sɔːs/","n.来源；根源；出处；原始资料"),
("sphere","/sfɪə(r)/","n.球体；范围；领域；界"),
("spill","/spɪl/","v.溢出；洒出；泄露 n.溢出"),
("spin","/spɪn/","v.旋转；纺纱；疾驰 n.旋转；兜风"),
("spirit","/ˈspɪrɪt/","n.精神；灵魂；情绪；勇气（复数）"),
("spite","/spaɪt/","n.恶意；怨恨；不顾"),
("splendid","/ˈsplendɪd/","adj.辉煌的；极好的；壮丽的"),
("split","/splɪt/","v.分裂；分开；劈开 n.分裂；裂口"),
("spoil","/spɔɪl/","v.宠坏；破坏；变质 n.战利品"),
("spread","/spred/","v.传播；展开；铺开 n.传播；范围"),
("spring","/sprɪŋ/","n.春天；泉；弹簧 v.涌现；跳跃；发源于"),
("stable","/ˈsteɪbl/","adj.稳定的；稳固的 n.马厩"),
("stale","/steɪl/","adj.不新鲜的；陈旧的；厌倦的"),
("statue","/ˈstætʃuː/","n.雕像；塑像"),
("status","/ˈsteɪtəs/","n.地位；状态；身份；情形"),
("steady","/ˈstedi/","adj.稳定的；稳固的；平稳的 v.使稳定"),
("steep","/stiːp/","adj.陡峭的；急剧的 v.浸泡"),
("stem","/stem/","n.茎；干；词干 v.阻止；源于；来自"),
("stick","/stɪk/","n.棍；棒；手杖 v.粘；刺；坚持"),
("stiff","/stɪf/","adj.僵硬的；严厉的；费劲的；不动的"),
("stimulate","/ˈstɪmjuleɪt/","v.刺激；激励；促进；激发"),
("stir","/stɜː(r)/","v.搅拌；激起；打动 n.搅拌；骚动"),
("stock","/stɒk/","n.库存；股票；股本；家系 v.储备；存货"),
("strain","/streɪn/","n.压力；张力；劳损 v.使紧张；拉伤；尽力"),
("strange","/streɪndʒ/","adj.奇怪的；陌生的；外地的"),
("strategy","/ˈstrætədʒi/","n.策略；战略；计谋"),
("strength","/streŋθ/","n.力量；实力；长处；强度"),
("stress","/stres/","n.压力；强调；重音 v.强调；重读"),
("strike","/straɪk/","v.打击；罢工；打动；突然想到 n.罢工；袭击"),
("string","/strɪŋ/","n.弦；线；细绳；一串 v.悬挂；缚"),
("strip","/strɪp/","n.条；带；狭长地带 v.剥去；脱去；剥夺"),
("stroke","/strəʊk/","n.中风；击；一笔；划水 v.抚摸；轻抚"),
("structure","/ˈstrʌktʃə(r)/","n.结构；构造；建筑物 v.构造；组织"),
("struggle","/ˈstrʌɡl/","n./v.挣扎；奋斗；努力；斗争"),
("studio","/ˈstjuːdiəʊ/","n.工作室；录音室；摄影棚；画室"),
("stuff","/stʌf/","n.东西；材料；素材 v.塞满；填塞"),
("style","/staɪl/","n.风格；样式；时尚；作风 v.设计；称呼"),
("subjective","/səbˈdʒektɪv/","adj.主观的；个人的"),
("submit","/səbˈmɪt/","v.提交；呈递；服从；屈服"),
("substance","/ˈsʌbstəns/","n.物质；实质；主旨；财产"),
("substitute","/ˈsʌbstɪtjuːt/","n.代替品；替补 v.替代；取代"),
("subtle","/ˈsʌtl/","adj.微妙的；细微的；敏锐的"),
("successful","/səkˈsesfl/","adj.成功的；如愿以偿的"),
("suck","/sʌk/","v.吸；吮；吸入；使卷入"),
("sudden","/ˈsʌdn/","adj.突然的；意外的；迅速的"),
("suffer","/ˈsʌfə(r)/","v.遭受；忍受；受苦；患病"),
("sufficient","/səˈfɪʃnt/","adj.足够的；充足的；充分的"),
("suggest","/səˈdʒest/","v.建议；提议；暗示；表明"),
("summary","/ˈsʌməri/","n.总结；摘要 adj.概括的；从速的"),
("super","/ˈsuːpə(r)/","adj.超级的；极好的；顶级的"),
("superior","/suːˈpɪəriə(r)/","adj.优越的；更好的；上级的 n.上级"),
("supply","/səˈplaɪ/","n./v.供应；供给；提供"),
("suppose","/səˈpəʊz/","v.假设；认为；料想；假定"),
("supreme","/suːˈpriːm/","adj.最高的；至上的；极度的"),
("surface","/ˈsɜːfɪs/","n.表面；外表；水面 v.浮出水面；显露"),
("surplus","/ˈsɜːpləs/","n.过剩；盈余 adj.过剩的；多余的"),
("surprise","/səˈpraɪz/","n.惊讶；意外；奇袭 v.使吃惊；突袭"),
("surround","/səˈraʊnd/","v.包围；环绕；围绕"),
("survey","/ˈsɜːveɪ/","n./v.调查；测量；勘测；审视"),
("survive","/səˈvaɪv/","v.幸存；活下来；比…活得长"),
("suspect","/səˈspekt/","v.怀疑；猜想 n.嫌疑犯 /ˈsʌspekt/ adj.可疑的"),
("suspend","/səˈspend/","v.悬挂；暂停；中止；推迟"),
("sustain","/səˈsteɪn/","v.维持；支撑；承受；遭受"),
("swallow","/ˈswɒləʊ/","v.吞下；轻信；抑制 n.燕子；吞咽"),
("swear","/sweə(r)/","v.发誓；宣誓；咒骂"),
("sweat","/swet/","n.汗；汗水 v.出汗；辛勤工作"),
("swell","/swel/","v.膨胀；肿胀；增大 n.浪潮；隆起"),
("swift","/swɪft/","adj.迅速的；敏捷的；立刻的"),
("swing","/swɪŋ/","v.摇摆；晃动；转身 n.秋千；摇摆"),
("switch","/swɪtʃ/","n.开关；转换；鞭子 v.转换；切换；关断"),
("tackle","/ˈtækl/","v.处理；对付；抢断 n.用具；阻截"),
("talent","/ˈtælənt/","n.天赋；才能；人才"),
("tame","/teɪm/","adj.驯服的；平淡的 v.驯服；制服"),
("target","/ˈtɑːɡɪt/","n.目标；靶子 v.瞄准；以…为目标"),
("tax","/tæks/","n.税；税款 v.向…征税；使负重担"),
("technical","/ˈteknɪkl/","adj.技术的；工艺的；专业的"),
("technique","/tekˈniːk/","n.技巧；技术；技能；手法"),
("tedious","/ˈtiːdiəs/","adj.冗长乏味的；使人厌烦的"),
("telescope","/ˈtelɪskəʊp/","n.望远镜 v.压缩；叠缩"),
("temporary","/ˈtemprəri/","adj.暂时的；临时的；短暂的"),
("tempt","/tempt/","v.引诱；诱惑；吸引；冒…的风险"),
("tend","/tend/","v.趋向；倾向于；照料；照顾"),
("tender","/ˈtendə(r)/","adj.温柔的；嫩的；脆弱的 v.提出；投标"),
("tense","/tens/","adj.紧张的；拉紧的 n.时态 v.拉紧"),
("terminal","/ˈtɜːmɪnl/","adj.末端的；晚期的 n.终点站；终端；航站楼"),
("terrible","/ˈterəbl/","adj.可怕的；糟糕的；严重的"),
("territory","/ˈterətri/","n.领土；领域；地盘；版图"),
("terror","/ˈterə(r)/","n.恐怖；恐惧；恐怖分子"),
("theory","/ˈθɪəri/","n.理论；学说；看法"),
("thick","/θɪk/","adj.厚的；浓的；密的；迟钝的"),
("thin","/θɪn/","adj.薄的；瘦的；稀薄的 v.变薄"),
("thorough","/ˈθʌrə/","adj.彻底的；详尽的；仔细的"),
("thought","/θɔːt/","n.想法；思考；思想；关心"),
("threat","/θret/","n.威胁；恐吓；凶兆"),
("thrill","/θrɪl/","n.激动；震颤；兴奋 v.使激动；使震颤"),
("thrive","/θraɪv/","v.繁荣；兴旺；茁壮成长"),
("throat","/θrəʊt/","n.喉咙；嗓子；喉部"),
("tone","/təʊn/","n.语气；音调；色调；气氛 v.使协调"),
("topic","/ˈtɒpɪk/","n.话题；主题；题目"),
("tough","/tʌf/","adj.坚韧的；艰难的；坚强的；强硬的"),
("trace","/treɪs/","v.追踪；追溯；描摹 n.痕迹；踪迹；微量"),
("track","/træk/","n.轨道；踪迹；跑道 v.跟踪；追踪"),
("tradition","/trəˈdɪʃn/","n.传统；惯例；传说"),
("traffic","/ˈtræfɪk/","n.交通；流量；通信量 v.交易；非法买卖"),
("tragedy","/ˈtrædʒədi/","n.悲剧；惨案；灾难"),
("trail","/treɪl/","n.小径；踪迹；拖尾 v.追踪；拖；落后"),
("train","/treɪn/","n.火车；列车；行列 v.训练；培训"),
("trait","/treɪt/","n.特征；品质；特性"),
("transfer","/trænsˈfɜː(r)/","v.转移；调动；换乘 /ˈtrænsfɜː(r)/ n.转移；转让"),
("transform","/trænsˈfɔːm/","v.转变；改变；改造；使改观"),
("transit","/ˈtrænzɪt/","n.运输；运送；中转 v.通过；运送"),
("translate","/trænsˈleɪt/","v.翻译；转化；转变；解释"),
("transparent","/trænsˈpærənt/","adj.透明的；易懂的；明显的"),
("transport","/trænsˈpɔːt/","v.运输；运送 /ˈtrænspɔːt/ n.交通；运输工具"),
("trap","/træp/","n.陷阱；圈套；困境 v.困住；设陷阱"),
("treat","/triːt/","v.对待；治疗；款待；处理 n.款待；乐事"),
("tremble","/ˈtrembl/","v.颤抖；颤动；摇晃 n.颤抖"),
("trend","/trend/","n.趋势；趋向；潮流 v.倾向；走向"),
("trial","/ˈtraɪəl/","n.审判；试验；试用；磨难 adj.试验的"),
("tribe","/traɪb/","n.部落；族；一群"),
("trick","/trɪk/","n.诡计；技巧；恶作剧 v.欺骗；哄骗"),
("trim","/trɪm/","v.修剪；削减；整理 adj.整洁的 n.修剪"),
("trip","/trɪp/","n.旅行；行程 v.绊倒；轻快地走"),
("triumph","/ˈtraɪəmf/","n.胜利；凯旋；成功 v.获胜；欢庆"),
("troop","/truːp/","n.军队；一群；部队 v.成群结队而行"),
("tropical","/ˈtrɒpɪkl/","adj.热带的；炎热的；热带植物的"),
("trust","/trʌst/","n./v.信任；信赖；委托；托付"),
("truth","/truːθ/","n.真相；真理；事实；真实性"),
("tube","/tjuːb/","n.管子；软管；地铁；管状物"),
("tune","/tjuːn/","n.曲调；音调；和谐 v.调音；调节；收听"),
("ultimate","/ˈʌltɪmət/","adj.最终的；根本的；极限的"),
("unaware","/ˌʌnəˈweə(r)/","adj.未觉察的；不知道的"),
("unconscious","/ʌnˈkɒnʃəs/","adj.无意识的；昏迷的；未察觉的"),
("undergo","/ˌʌndəˈɡəʊ/","v.经历；遭受；承受"),
("underground","/ˌʌndəˈɡraʊnd/","adj.地下的；秘密的 n.地铁 adv.在地下"),
("underline","/ˌʌndəˈlaɪn/","v.在…下划线；强调；突出"),
("understand","/ˌʌndəˈstænd/","v.理解；懂；谅解；获悉"),
("undertake","/ˌʌndəˈteɪk/","v.承担；着手做；承诺；同意"),
("undo","/ʌnˈduː/","v.撤销；解开；消除；使复原"),
("unexpected","/ˌʌnɪkˈspektɪd/","adj.意外的；出乎意料的"),
("unfair","/ˌʌnˈfeə(r)/","adj.不公平的；不公正的；偏袒的"),
("unique","/juˈniːk/","adj.独特的；唯一的；独一无二的"),
("unity","/ˈjuːnəti/","n.团结；统一；一致性；整体"),
("universal","/ˌjuːnɪˈvɜːsl/","adj.普遍的；全世界的；通用的"),
("universe","/ˈjuːnɪvɜːs/","n.宇宙；天地万物；领域"),
("unlike","/ˌʌnˈlaɪk/","prep.不像；与…不同 adj.不同的"),
("update","/ˌʌpˈdeɪt/","v.更新；使现代化 n.最新消息；更新"),
("uphold","/ʌpˈhəʊld/","v.支持；维护； uphold；维持"),
("upset","/ʌpˈset/","v.使心烦；打乱；推翻 adj.心烦的；不适的 n.混乱"),
("upward","/ˈʌpwəd/","adj.向上的；上升的 adv.向上；往上"),
("urban","/ˈɜːbən/","adj.城市的；都市的；城镇的"),
("urge","/ɜːdʒ/","v.催促；力劝；驱策 n.冲动；强烈欲望"),
("urgent","/ˈɜːdʒənt/","adj.紧急的；急迫的；迫切的"),
("usage","/ˈjuːsɪdʒ/","n.用法；使用；惯用法；习俗"),
("useful","/ˈjuːsfl/","adj.有用的；实用的；有益的"),
("useless","/ˈjuːsləs/","adj.无用的；无效的；无价值的"),
("usual","/ˈjuːʒuəl/","adj.通常的；惯常的；平常的"),
("utility","/juːˈtɪləti/","n.效用；实用；公用事业 adj.实用的"),
("vague","/veɪɡ/","adj.模糊的；含糊的；不明确的"),
("valid","/ˈvælɪd/","adj.有效的；合理的；合法的；有根据的"),
("valuable","/ˈvæljuəbl/","adj.有价值的；贵重的；宝贵的 n.贵重物品"),
("value","/ˈvæljuː/","n.价值；数值；重要性 v.重视；评价"),
("vanish","/ˈvænɪʃ/","v.消失；突然不见；灭绝"),
("variable","/ˈveəriəbl/","adj.可变的；易变的 n.变量；可变因素"),
("variation","/ˌveəriˈeɪʃn/","n.变化；变动；变体；差异"),
("variety","/vəˈraɪəti/","n.多样；种类；种种；变化"),
("various","/ˈveəriəs/","adj.各种各样的；不同的；多方面的"),
("vary","/ˈveəri/","v.变化；不同；改变；使多样化"),
("vast","/vɑːst/","adj.广阔的；巨大的；大量的；浩瀚的"),
("vehicle","/ˈviːəkl/","n.车辆；交通工具；媒介；手段"),
("venture","/ˈventʃə(r)/","n.冒险；企业；投机 v.冒险；大胆表示"),
("version","/ˈvɜːʃn/","n.版本；说法；译文；变体"),
("vertical","/ˈvɜːtɪkl/","adj.垂直的；竖的；纵向的 n.垂直线"),
("victim","/ˈvɪktɪm/","n.受害者；牺牲品；受骗者"),
("view","/vjuː/","n.观点；景色；视野 v.看待；观看；考虑"),
("vigorous","/ˈvɪɡərəs/","adj.精力充沛的；有力的；强烈的"),
("violate","/ˈvaɪəleɪt/","v.违反；侵犯；亵渎；妨碍"),
("virtual","/ˈvɜːtʃuəl/","adj.虚拟的；实质上的；事实上的"),
("virtue","/ˈvɜːtʃuː/","n.美德；优点；德行；功效"),
("visible","/ˈvɪzəbl/","adj.可见的；明显的；看得见的"),
("vision","/ˈvɪʒn/","n.视力；视野；愿景；幻想"),
("visual","/ˈvɪʒuəl/","adj.视觉的；视力的；看的 n.画面"),
("vital","/ˈvaɪtl/","adj.至关重要的；生命的；充满活力的"),
("vivid","/ˈvɪvɪd/","adj.生动的；鲜明的；清晰的"),
("vocabulary","/vəˈkæbjələri/","n.词汇；词汇量；词表"),
("volcano","/vɒlˈkeɪnəʊ/","n.火山"),
("volt","/vəʊlt/","n.伏特（电压单位）"),
("volume","/ˈvɒljuːm/","n.体积；音量；卷；量；容量"),
("voluntary","/ˈvɒləntri/","adj.自愿的；志愿的；自发的"),
("vote","/vəʊt/","n./v.投票；选举；表决；选票"),
("voyage","/ˈvɔɪɪdʒ/","n.航行；航海；航天 v.航行"),
("wage","/weɪdʒ/","n.工资；报酬 v.进行；发动"),
("waist","/weɪst/","n.腰；腰部；腰围"),
("wander","/ˈwɒndə(r)/","v.漫步；徘徊；走神；离题"),
("wealth","/welθ/","n.财富；财产；丰富；大量"),
("weapon","/ˈwepən/","n.武器；兵器；手段"),
("weary","/ˈwɪəri/","adj.疲倦的；厌倦的 v.使疲倦；生厌"),
("wedding","/ˈwedɪŋ/","n.婚礼；结婚纪念；结合"),
("weed","/wiːd/","n.杂草；野草 v.除草；剔除"),
("weekly","/ˈwiːkli/","adj.每周的；周刊的 adv.每周 n.周刊"),
("welfare","/ˈwelfeə(r)/","n.福利；幸福；社会保障"),
("whereas","/ˌweərˈæz/","conj.然而；鉴于；反之"),
("whilst","/waɪlst/","conj.当…时；同时；虽然"),
("whip","/wɪp/","n.鞭子；抽打 v.鞭打；搅打；突然移动"),
("whisper","/ˈwɪspə(r)/","v./n.低语；耳语；私语；传闻"),
("whistle","/ˈwɪsl/","n.哨子；口哨；汽笛 v.吹口哨；呼啸"),
("widen","/ˈwaɪdn/","v.拓宽；加宽；扩大；变宽"),
("widespread","/ˈwaɪdspred/","adj.广泛的；普遍的；分布广的"),
("widow","/ˈwɪdəʊ/","n.寡妇；遗孀 v.使成寡妇"),
("willing","/ˈwɪlɪŋ/","adj.愿意的；乐意的；自愿的"),
("wing","/wɪŋ/","n.翅膀；翼；侧厅；派别 v.飞；机翼"),
("wipe","/waɪp/","v.擦；抹；拭去；消灭 n.擦拭"),
("wire","/ˈwaɪə(r)/","n.金属丝；电线；电缆 v.接线；发电报"),
("wisdom","/ˈwɪzdəm/","n.智慧；明智；学识；格言"),
("withdraw","/wɪðˈdrɔː/","v.撤回；收回；取（款）；退出"),
("withstand","/wɪðˈstænd/","v.经受住；承受；抵抗"),
("witness","/ˈwɪtnəs/","n.目击者；证人；证据 v.目睹；作证"),
("wooden","/ˈwʊdn/","adj.木制的；木头的；呆板的"),
("wool","/wʊl/","n.羊毛；毛线；毛织物"),
("worldwide","/ˈwɜːldwaɪd/","adj.全世界的 adv.在世界各地"),
("worship","/ˈwɜːʃɪp/","n./v.崇拜；敬奉；崇敬"),
("worthy","/ˈwɜːði/","adj.值得的；有价值的；配得上的"),
("wound","/wuːnd/","n.伤口；创伤 v.使受伤；伤害"),
("wrap","/ræp/","v.包裹；缠绕；覆盖 n.披肩；包装"),
("wreck","/rek/","v.破坏；毁坏；失事 n.残骸；失事船"),
("yard","/jɑːd/","n.院子；庭院；码（长度单位）"),
("yawn","/jɔːn/","v.打哈欠；裂开 n.哈欠；裂口"),
("yearly","/ˈjɜːli/","adj.每年的；一年一度的 adv.每年"),
("yield","/jiːld/","v.产出；屈服；让步 n.产量；收益"),
("youngster","/ˈjʌŋstə(r)/","n.年轻人；少年；儿童"),
("zone","/zəʊn/","n.区域；地带；区 v.分区；划区"),
("zoom","/zuːm/","v.急速移动；变焦；猛涨 n. Zoom；嗡嗡声"),
]

# 去重（保留顺序），剔除与内置 466 词重复者
seen=set()
words=[]
for w,ph,me in RAW:
    if w in existing or w in seen:
        continue
    seen.add(w)
    words.append({"word":w,"phonetic":ph,"meaning":me,
                  "root":"","collocation":[],"synonym":[],"antonym":[],"example":"","example2":""})

if len(words)<600:
    raise SystemExit("词数不足600：%d"%len(words))

words=words[:600]
out={"version":"20260913a",
     "comment":"四级高频词增量第一批（公开词频表 g-z 段，仅收单词与释义，自撰中文，规避版权；与内置466词不重复）",
     "words":words}
path=os.path.join(root,'assets','data','vocab-cet4-ext.json')
json.dump(out,open(path,'w',encoding='utf-8'),ensure_ascii=False,indent=2)
log=os.path.join(root,'_gen_vocab.log')
open(log,'w',encoding='utf-8').write('TOTAL=%d\nDUP_EXISTING_DROPPED=%d\n'%(len(words),len(existing & set(w for w,_,_ in RAW))))
