# -*- coding: utf-8 -*-
"""
R88-J 位置选择组件（方案 A）—— 注入 assets/xt-region.js（**LF**）。
在既有 XT_LOC_PICK 基础上追加：
  - RECENT_KEY ('xt_region_recent') 常用城市 LRU ≤8
  - openPicker(opts, cb)  微信式「发送位置」选择层：
      顶部搜索框 + 静态图位(纯 CSS/SVG, 无外链) + Pin 图标 + 地址候选列表 + 常用城市 + 确认按钮
      搜索走 XT_REGION.search()（省/市/区联想）；也支持「用当前位置」调用 locate+reverseGeocode。
      确认 = cb(text)；取消 = cb(null)。全程仅输出 text，坐标绝不进字符串。
  - 复用: _clipText / _writeLast / isCoordinateText / _safeLS
约束：ES2017（var/function，无 ?. ?? 展开 反引号）；禁原生弹窗；LF 行尾。
用法：python tools/r88j_patch_region.py [--apply]
"""
import os
import sys

BASE = r"D:\下载的文件\学习工作台"
APPLY = ("--apply" in sys.argv)
JS = os.path.join(BASE, r"assets\xt-region.js")
LF = "\n"

OLD = (
    "  window.XT_LOC_PICK = {\n"
    "    pick: pick,\n"
    "    last: last,\n"
    "    isCoordinateText: isCoordinateText,\n"
    "    LAST_KEY: LAST_KEY\n"
    "  };\n"
    "\n"
    "})();\n"
)

NEW = (
    "  /* ---------------- R88-J：常用城市（LRU ≤8） ---------------- */\n"
    "  var RECENT_KEY = 'xt_region_recent';\n"
    "  var RECENT_MAX = 8;\n"
    "\n"
    "  /** 读常用城市列表（失败返回 []）。 */\n"
    "  function recentList() {\n"
    "    var ls = _safeLS();\n"
    "    if (!ls) return [];\n"
    "    var raw = null;\n"
    "    try { raw = ls.getItem(RECENT_KEY); } catch (e) { raw = null; }\n"
    "    if (!raw) return [];\n"
    "    var arr = null;\n"
    "    try { arr = JSON.parse(raw); } catch (e2) { arr = null; }\n"
    "    if (Object.prototype.toString.call(arr) !== '[object Array]') return [];\n"
    "    var out = [], i, s;\n"
    "    for (i = 0; i < arr.length; i++) {\n"
    "      s = (arr[i] == null) ? '' : String(arr[i]).replace(/^\\s+|\\s+$/g, '');\n"
    "      if (s && out.indexOf(s) < 0) out.push(s);\n"
    "    }\n"
    "    return out;\n"
    "  }\n"
    "\n"
    "  /** 把一个地址文本推入常用城市（去重 + LRU 置顶 + ≤8，失败静默）。 */\n"
    "  function recentPush(text) {\n"
    "    var t = (text == null) ? '' : String(text).replace(/^\\s+|\\s+$/g, '');\n"
    "    if (!t) return;\n"
    "    var ls = _safeLS();\n"
    "    if (!ls) return;\n"
    "    var list = recentList();\n"
    "    var out = [t], i;\n"
    "    for (i = 0; i < list.length; i++) { if (list[i] !== t) out.push(list[i]); }\n"
    "    if (out.length > RECENT_MAX) out = out.slice(0, RECENT_MAX);\n"
    "    try { ls.setItem(RECENT_KEY, JSON.stringify(out)); } catch (e) {}\n"
    "  }\n"
    "\n"
    "  /* ---------------- R88-J：微信式位置选择组件（方案 A） ----------------\n"
    "   * 说明：不引第三方地图库。地图区域用【纯 CSS + 内联 SVG】绘制的静态示意（无外链图片、\n"
    "   *   无网络依赖），叠加 data-icon=\"map-pin\" 的 Pin。地址候选来自 XT_REGION.search()\n"
    "   *   省/市/区联想 + 「用当前位置」的逆地理编码结果。确认仅回传 text（坐标绝不进字符串）。\n"
    "   */\n"
    "  var _pickSeq = 0;\n"
    "  var PIN_SVG = '<svg viewBox=\"0 0 24 24\" width=\"30\" height=\"30\" fill=\"none\" stroke=\"#fff\" '+\n"
    "    'stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0z\"></path><circle cx=\"12\" cy=\"10\" r=\"3\"></circle></svg>';\n"
    "  var SEARCH_SVG = '<svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"#9aa3b2\" '+\n"
    "    'stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"11\" cy=\"11\" r=\"7\"></circle><path d=\"M21 21l-4.3-4.3\"></path></svg>';\n"
    "\n"
    "  function _escAttr(s) {\n"
    "    return String(s == null ? '' : s).replace(/[&<>\"']/g, function (c) {\n"
    "      return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;', \"'\": '&#39;' })[c];\n"
    "    });\n"
    "  }\n"
    "\n"
    "  function openPicker(opts, cb) {\n"
    "    var o = opts || {};\n"
    "    var done = (typeof cb === 'function') ? cb : function () {};\n"
    "    var title = o.title || '选择位置';\n"
    "    var confirmText = o.confirmText || '确认';\n"
    "    var initText = (o.current == null) ? '' : String(o.current);\n"
    "\n"
    "    var rootId = '__xtLocPicker' + (_pickSeq++);\n"
    "    var root = document.createElement('div');\n"
    "    root.id = rootId;\n"
    "    root.className = 'xtlp';\n"
    "\n"
    "    var STYLE =\n"
    "      '.xtlp{position:fixed;inset:0;z-index:1200;background:#f5f7fb;display:flex;flex-direction:column}'+\n"
    "      '.xtlp *{box-sizing:border-box}'+\n"
    "      '.xtlp-head{display:flex;align-items:center;gap:8px;padding:10px 12px;background:#fff;border-bottom:1px solid #e6e9f0}'+\n"
    "      '.xtlp-back{border:1px solid #e6e9f0;background:transparent;border-radius:10px;padding:6px 10px;font-size:13px;color:#6b7280;cursor:pointer}'+\n"
    "      '.xtlp-title{font-size:16px;font-weight:700;color:#1f2937}'+\n"
    "      '.xtlp-ok{margin-left:auto;border:none;border-radius:10px;padding:8px 16px;font-size:14px;font-weight:700;color:#fff;background:#5B8DEF;cursor:pointer}'+\n"
    "      '.xtlp-ok[disabled]{opacity:.45;cursor:default}'+\n"
    "      '.xtlp-search{display:flex;align-items:center;gap:8px;margin:10px 12px;padding:9px 12px;border-radius:12px;background:#fff;border:1px solid #e6e9f0}'+\n"
    "      '.xtlp-search input{flex:1;border:none;outline:none;background:transparent;font-size:14px;color:#1f2937}'+\n"
    "      '.xtlp-map{position:relative;height:168px;margin:0 12px;border-radius:14px;overflow:hidden;'+\n"
    "        'background:linear-gradient(135deg,#dbe7f7,#eef4fb 55%,#e5f0e6);border:1px solid #e6e9f0}'+\n"
    "      '.xtlp-map::before{content:\"\";position:absolute;left:-10%;top:38%;width:120%;height:10px;background:rgba(255,255,255,.75);'+\n"
    "        'transform:rotate(-8deg);box-shadow:0 34px 0 rgba(255,255,255,.55),0 -30px 0 rgba(255,255,255,.4)}'+\n"
    "      '.xtlp-map::after{content:\"\";position:absolute;left:30%;top:-10%;width:10px;height:120%;background:rgba(255,255,255,.55);'+\n"
    "        'transform:rotate(12deg)}'+\n"
    "      '.xtlp-pin{position:absolute;left:50%;top:46%;transform:translate(-50%,-100%);width:40px;height:40px;border-radius:50%;'+\n"
    "        'background:#eb5757;display:flex;align-items:center;justify-content:center;box-shadow:0 6px 16px rgba(235,87,87,.4)}'+\n"
    "      '.xtlp-pin::after{content:\"\";position:absolute;left:50%;bottom:-6px;transform:translateX(-50%) rotate(45deg);width:14px;height:14px;'+\n"
    "        'background:#eb5757;border-radius:2px}'+\n"
    "      '.xtlp-pin svg{position:relative;z-index:1}'+\n"
    "      '.xtlp-curline{position:absolute;left:12px;right:12px;bottom:10px;background:rgba(31,41,55,.82);color:#fff;border-radius:10px;'+\n"
    "        'padding:7px 12px;font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}'+\n"
    "      '.xtlp-list{flex:1;overflow-y:auto;margin:10px 12px 0;background:#fff;border-radius:14px;border:1px solid #e6e9f0}'+\n"
    "      '.xtlp-sec{padding:10px 14px 4px;font-size:12px;font-weight:700;color:#9aa3b2;letter-spacing:.5px}'+\n"
    "      '.xtlp-item{display:flex;align-items:center;gap:10px;padding:12px 14px;font-size:14px;color:#1f2937;cursor:pointer;border-top:1px solid #eef1f6}'+\n"
    "      '.xtlp-item:active{background:#f5f7fb}'+\n"
    "      '.xtlp-item.on{color:#5B8DEF;font-weight:700}'+\n"
    "      '.xtlp-item .xtlp-tick{margin-left:auto;color:#5B8DEF;flex:none}'+\n"
    "      '.xtlp-sub{color:#9aa3b2;font-size:12px}'+\n"
    "      '.xtlp-empty{padding:26px 14px;text-align:center;color:#9aa3b2;font-size:13px}'+\n"
    "      '.xtlp-foot{padding:10px 12px 16px;display:flex;gap:10px;background:#fff;border-top:1px solid #e6e9f0}'+\n"
    "      '.xtlp-loc{flex:1;border:1px solid #5B8DEF;background:transparent;color:#5B8DEF;border-radius:10px;padding:10px;font-size:14px;cursor:pointer}'+\n"
    "      '.xtlp-cancel{flex:none;border:1px solid #e6e9f0;background:transparent;color:#6b7280;border-radius:10px;padding:10px 18px;font-size:14px;cursor:pointer}';\n"
    "\n"
    "    var style = document.createElement('style');\n"
    "    style.textContent = STYLE;\n"
    "    root.appendChild(style);\n"
    "\n"
    "    var html = '';\n"
    "    html += '<div class=\"xtlp-head\"><button type=\"button\" class=\"xtlp-back\" data-act=\"cancel\">取消</button>';\n"
    "    html += '<span class=\"xtlp-title\">' + _escAttr(title) + '</span>';\n"
    "    html += '<button type=\"button\" class=\"xtlp-ok\" data-act=\"ok\" disabled>' + _escAttr(confirmText) + '</button></div>';\n"
    "    html += '<div class=\"xtlp-search\">' + SEARCH_SVG +\n"
    "      '<input type=\"text\" class=\"xtlp-input\" placeholder=\"搜索地址 / 省 / 市 / 区，如：天河、杭州\" autocomplete=\"off\"></div>';\n"
    "    html += '<div class=\"xtlp-map\"><div class=\"xtlp-pin\">' + PIN_SVG + '</div>' +\n"
    "      '<div class=\"xtlp-curline\">尚未选择位置</div></div>';\n"
    "    html += '<div class=\"xtlp-list\"></div>';\n"
    "    html += '<div class=\"xtlp-foot\"><button type=\"button\" class=\"xtlp-loc\" data-act=\"loc\">用当前位置</button>' +\n"
    "      '<button type=\"button\" class=\"xtlp-cancel\" data-act=\"cancel\">取消</button></div>';\n"
    "\n"
    "    var body = document.createElement('div');\n"
    "    body.className = 'xtlp-body';\n"
    "    body.innerHTML = html;\n"
    "    root.appendChild(body);\n"
    "    document.body.appendChild(root);\n"
    "\n"
    "    var inputEl = root.querySelector('.xtlp-input');\n"
    "    var listEl = root.querySelector('.xtlp-list');\n"
    "    var curlineEl = root.querySelector('.xtlp-curline');\n"
    "    var okEl = root.querySelector('.xtlp-ok');\n"
    "    var chosen = '';\n"
    "    var kw = '';\n"
    "    var closed = false;\n"
    "\n"
    "    function setChosen(text, sub) {\n"
    "      chosen = (text == null) ? '' : String(text).replace(/^\\s+|\\s+$/g, '');\n"
    "      if (chosen) {\n"
    "        curlineEl.textContent = chosen;\n"
    "        okEl.removeAttribute('disabled');\n"
    "      } else {\n"
    "        curlineEl.textContent = sub || '尚未选择位置';\n"
    "        okEl.setAttribute('disabled', 'disabled');\n"
    "      }\n"
    "      var items = listEl.querySelectorAll('.xtlp-item');\n"
    "      for (var i = 0; i < items.length; i++) {\n"
    "        if (items[i].getAttribute('data-text') === chosen) items[i].className = 'xtlp-item on';\n"
    "        else items[i].className = 'xtlp-item';\n"
    "      }\n"
    "    }\n"
    "\n"
    "    function itemRow(text, sub) {\n"
    "      var cls = 'xtlp-item' + (text === chosen ? ' on' : '');\n"
    "      var subHtml = sub ? ' <span class=\"xtlp-sub\">' + _escAttr(sub) + '</span>' : '';\n"
    "      return '<div class=\"' + cls + '\" data-text=\"' + _escAttr(text) + '\">' + _escAttr(text) + subHtml +\n"
    "        (text === chosen ? '<span class=\"xtlp-tick\">✓</span>' : '') + '</div>';\n"
    "    }\n"
    "\n"
    "    function renderList() {\n"
    "      var html2 = '';\n"
    "      var i, R;\n"
    "      if (kw) {\n"
    "        R = window.XT_REGION;\n"
    "        var hits = (R && typeof R.search === 'function') ? R.search(kw, 40) : [];\n"
    "        if (!hits.length) { listEl.innerHTML = '<div class=\"xtlp-empty\">没找到「' + _escAttr(kw) + '」，换个关键词试试</div>'; return; }\n"
    "        html2 += '<div class=\"xtlp-sec\">搜索结果</div>';\n"
    "        for (i = 0; i < hits.length; i++) {\n"
    "          var sub = (hits[i].province && hits[i].province !== hits[i].city) ? hits[i].province : '';\n"
    "          html2 += itemRow(hits[i].text, sub);\n"
    "        }\n"
    "        listEl.innerHTML = html2;\n"
    "        return;\n"
    "      }\n"
    "      var recent = recentList();\n"
    "      if (recent.length) {\n"
    "        html2 += '<div class=\"xtlp-sec\">常用城市</div>';\n"
    "        for (i = 0; i < recent.length; i++) html2 += itemRow(recent[i], '常用');\n"
    "      }\n"
    "      R = window.XT_REGION;\n"
    "      var provs = (R && typeof R.provinces === 'function') ? R.provinces() : [];\n"
    "      if (provs.length) {\n"
    "        html2 += '<div class=\"xtlp-sec\">热门 / 全部省份</div>';\n"
    "        for (i = 0; i < provs.length && i < 12; i++) html2 += itemRow(provs[i], '省');\n"
    "      }\n"
    "      if (!html2) html2 = '<div class=\"xtlp-empty\">暂无可选地址</div>';\n"
    "      listEl.innerHTML = html2;\n"
    "    }\n"
    "\n"
    "    function finish(text) {\n"
    "      if (closed) return;\n"
    "      closed = true;\n"
    "      try { if (root.parentNode) root.parentNode.removeChild(root); } catch (e) {}\n"
    "      document.removeEventListener('keydown', onKey);\n"
    "      if (text) recentPush(text);\n"
    "      done(text || null);\n"
    "    }\n"
    "\n"
    "    function onKey(e) {\n"
    "      var k = e && e.key;\n"
    "      if (k === 'Escape' || k === 'Esc') finish(null);\n"
    "    }\n"
    "\n"
    "    var kwTimer = null;\n"
    "    inputEl.addEventListener('input', function () {\n"
    "      if (kwTimer) clearTimeout(kwTimer);\n"
    "      kwTimer = setTimeout(function () {\n"
    "        kw = String(inputEl.value || '').replace(/^\\s+|\\s+$/g, '');\n"
    "        renderList();\n"
    "      }, 160);\n"
    "    });\n"
    "\n"
    "    listEl.addEventListener('click', function (ev) {\n"
    "      var node = ev.target;\n"
    "      while (node && node !== listEl && !(node.getAttribute && node.getAttribute('data-text') !== null)) { node = node.parentNode; }\n"
    "      if (!node || node === listEl) return;\n"
    "      var t = node.getAttribute('data-text');\n"
    "      if (t == null) return;\n"
    "      setChosen(t, '');\n"
    "    });\n"
    "\n"
    "    root.addEventListener('click', function (ev) {\n"
    "      var n = ev.target;\n"
    "      while (n && n !== root && !(n.getAttribute && n.getAttribute('data-act'))) { n = n.parentNode; }\n"
    "      if (!n || n === root) return;\n"
    "      var act = n.getAttribute('data-act');\n"
    "      if (act === 'cancel') { finish(null); return; }\n"
    "      if (act === 'ok') { if (chosen) finish(chosen); return; }\n"
    "      if (act === 'loc') {\n"
    "        locBusy = true;\n"
    "        setChosen('', '正在定位…');\n"
    "        locate(function (r) {\n"
    "          if (closed) return;\n"
    "          if (!r || r.ok === false) { setChosen('', '定位失败，可搜索或手动输入'); locBusy = false; _failToast(); return; }\n"
    "          setChosen('', '已获取坐标，正在解析地址…');\n"
    "          reverseGeocode(r.lat, r.lng, function (g) {\n"
    "            if (closed) return;\n"
    "            locBusy = false;\n"
    "            if (!g || !g.text) { setChosen('', '地址解析失败，可搜索或手动输入'); return; }\n"
    "            var txt = g.text;\n"
    "            var RR = window.XT_REGION;\n"
    "            if ((g.province || g.city) && RR && typeof RR.textOf === 'function') {\n"
    "              var t2 = RR.textOf(g.province, g.city, g.district);\n"
    "              if (t2) txt = t2;\n"
    "            }\n"
    "            setChosen(_clipText(txt), '');\n"
    "          });\n"
    "        });\n"
    "        return;\n"
    "      }\n"
    "    });\n"
    "\n"
    "    var locBusy = false;\n"
    "    document.addEventListener('keydown', onKey);\n"
    "\n"
    "    if (initText) setChosen(initText, '');\n"
    "    renderList();\n"
    "    try { if (inputEl.focus) inputEl.focus(); } catch (e9) {}\n"
    "  }\n"
    "\n"
    "  window.XT_LOC_PICK = {\n"
    "    pick: pick,\n"
    "    last: last,\n"
    "    isCoordinateText: isCoordinateText,\n"
    "    LAST_KEY: LAST_KEY,\n"
    "    RECENT_KEY: RECENT_KEY,\n"
    "    openPicker: openPicker,\n"
    "    recent: recentList\n"
    "  };\n"
    "\n"
    "})();\n"
)


def main():
    raw = open(JS, "rb").read()
    txt = raw.decode("utf-8")
    # xt-region.js is LF; guard anyway
    assert "\r\n" not in txt, "xt-region.js 出现 CRLF，与预期 LF 不符"
    assert txt.count(OLD) == 1, "OLD 锚点命中 %d 次" % txt.count(OLD)
    out_txt = txt.replace(OLD, NEW, 1)
    assert "\r\n" not in out_txt
    out = out_txt.encode("utf-8")
    print("APPLY=%s" % APPLY)
    print("xt-region.js before=%d after=%d delta=%+d" % (len(raw), len(out), len(out) - len(raw)))
    if APPLY:
        open(JS, "wb").write(out)
        b = open(JS, "rb").read()
        crlf = b.count(b"\r\n"); lone_lf = b.count(b"\n") - crlf; lone_cr = b.count(b"\r") - crlf
        print("  [js-after] bytes=%d CRLF=%d loneLF=%d loneCR=%d" % (len(b), crlf, lone_lf, lone_cr))


if __name__ == "__main__":
    main()
